global cn.ibizlab.pms.core.zentao.service.IStoryService  storyService;
global cn.ibizlab.pms.core.zentao.domain.Story et;

    no-loop
    rule "storygetstoryspec"
    ruleflow-group "8a35251dd9a6667f40d9079f7eab62e6"
    when
    then
    cn.ibizlab.pms.core.zentao.domain.Story actionLogicDE =new cn.ibizlab.pms.core.zentao.domain.Story();
    et.copyTo(actionLogicDE,true);
    storyService.getStorySpec(actionLogicDE);
    end

