global cn.ibizlab.pms.core.zentao.service.IStoryService  storyService;
import cn.ibizlab.pms.util.helper.CachedBeanCopier;
global cn.ibizlab.pms.core.zentao.domain.Story et;

    no-loop
    rule "storygetstoryspec"
    ruleflow-group "8a35251dd9a6667f40d9079f7eab62e6"
    when
    then
    cn.ibizlab.pms.core.zentao.domain.Story actionLogicDE =new cn.ibizlab.pms.core.zentao.domain.Story();
    CachedBeanCopier.copy(et, actionLogicDE);
    storyService.getStorySpec(actionLogicDE);
    end

