import ProductProductExpView from '@/widgets/product/product-exp-view-portlet/product-exp-view-portlet.vue';
import ActionAllTrends from '@/widgets/action/all-trends-portlet/all-trends-portlet.vue';
import MyWork from '@/widgets/app/my-work-portlet/my-work-portlet.vue';
import BugAssignedToMeBug from '@/widgets/bug/assigned-to-me-bug-portlet/assigned-to-me-bug-portlet.vue';
import TaskAssignToMe from '@/widgets/task/assign-to-me-portlet/assign-to-me-portlet.vue';
import ProductTextExpView from '@/widgets/product/text-exp-view-portlet/text-exp-view-portlet.vue';
import ProjectProjectExpView from '@/widgets/project/project-exp-view-portlet/project-exp-view-portlet.vue';
import ProductProductStatusChart from '@/widgets/product/product-status-chart-portlet/product-status-chart-portlet.vue';
import CaseMeCreateCase from '@/widgets/case/me-create-case-portlet/me-create-case-portlet.vue';
import TodoMyUpcoming from '@/widgets/todo/my-upcoming-portlet/my-upcoming-portlet.vue';
import CaseTestMainDetail from '@/widgets/case/test-main-detail-portlet/test-main-detail-portlet.vue';
import CaseMainDetail from '@/widgets/case/main-detail-portlet/main-detail-portlet.vue';
import CaseCaseLastrunner from '@/widgets/case/case-lastrunner-portlet/case-lastrunner-portlet.vue';
import CaseCaseLastrunnerProject from '@/widgets/case/case-lastrunner-project-portlet/case-lastrunner-project-portlet.vue';
import CaseCaseModule from '@/widgets/case/case-module-portlet/case-module-portlet.vue';
import CaseCaseModuleProject from '@/widgets/case/case-module-project-portlet/case-module-project-portlet.vue';
import CaseCaseType from '@/widgets/case/case-type-portlet/case-type-portlet.vue';
import CaseCaseTypeProject from '@/widgets/case/case-type-project-portlet/case-type-project-portlet.vue';
import CaseCaseResult from '@/widgets/case/case-result-portlet/case-result-portlet.vue';
import CaseTestDashboardQuickAction from '@/widgets/case/test-dashboard-quick-action-portlet/test-dashboard-quick-action-portlet.vue';
import CaseDashboardQuickAction from '@/widgets/case/dashboard-quick-action-portlet/dashboard-quick-action-portlet.vue';
import CaseCaseResultProject from '@/widgets/case/case-result-project-portlet/case-result-project-portlet.vue';
import CaseMainInfo from '@/widgets/case/main-info-portlet/main-info-portlet.vue';
import CaseTotalCurOpenedCase from '@/widgets/case/total-cur-opened-case-portlet/total-cur-opened-case-portlet.vue';
import ProductProductMainToolbar from '@/widgets/product/product-main-toolbar-portlet/product-main-toolbar-portlet.vue';
import ProductProductInfo from '@/widgets/product/product-info-portlet/product-info-portlet.vue';
import ProductUnClosedProduct from '@/widgets/product/un-closed-product-portlet/un-closed-product-portlet.vue';
import IbzLibIbzLibMain from '@/widgets/ibz-lib/ibz-lib-main-portlet/ibz-lib-main-portlet.vue';
import IbzLibIbzLibCz from '@/widgets/ibz-lib/ibz-lib-cz-portlet/ibz-lib-cz-portlet.vue';
import BurnBurnDownChart from '@/widgets/burn/burn-down-chart-portlet/burn-down-chart-portlet.vue';
import IbzReportMyReport from '@/widgets/ibz-report/my-report-portlet/my-report-portlet.vue';
import IbzProjectMemberRelatedMembers from '@/widgets/ibz-project-member/related-members-portlet/related-members-portlet.vue';
import StoryBaseInfo from '@/widgets/story/base-info-portlet/base-info-portlet.vue';
import StoryAssignedToMeStory from '@/widgets/story/assigned-to-me-story-portlet/assigned-to-me-story-portlet.vue';
import StoryTotalCurOpenedStoryStage from '@/widgets/story/total-cur-opened-story-stage-portlet/total-cur-opened-story-stage-portlet.vue';
import StoryTotalCurOpenedStoryPri from '@/widgets/story/total-cur-opened-story-pri-portlet/total-cur-opened-story-pri-portlet.vue';
import StoryMainToolbar from '@/widgets/story/main-toolbar-portlet/main-toolbar-portlet.vue';
import StoryStoryRelated from '@/widgets/story/story-related-portlet/story-related-portlet.vue';
import StoryStoryspec from '@/widgets/story/storyspec-portlet/storyspec-portlet.vue';
import TodoTodoaction from '@/widgets/todo/todoaction-portlet/todoaction-portlet.vue';
import TodoTodoBase from '@/widgets/todo/todo-base-portlet/todo-base-portlet.vue';
import TodoTodoDesc from '@/widgets/todo/todo-desc-portlet/todo-desc-portlet.vue';
import TodoTodoDashboardActions from '@/widgets/todo/todo-dashboard-actions-portlet/todo-dashboard-actions-portlet.vue';
import UserYearWorkStatsMonthOpenedBugAndCase from '@/widgets/user-year-work-stats/month-opened-bug-and-case-portlet/month-opened-bug-and-case-portlet.vue';
import UserYearWorkStatsFinishTaskAndBug from '@/widgets/user-year-work-stats/finish-task-and-bug-portlet/finish-task-and-bug-portlet.vue';
import UserYearWorkStatsMonthOpenedStory from '@/widgets/user-year-work-stats/month-opened-story-portlet/month-opened-story-portlet.vue';
import ProjectUnClosedProject from '@/widgets/project/un-closed-project-portlet/un-closed-project-portlet.vue';
import ProjectUndoneProject from '@/widgets/project/undone-project-portlet/undone-project-portlet.vue';
import ProjectProjectMainToolbar from '@/widgets/project/project-main-toolbar-portlet/project-main-toolbar-portlet.vue';
import ProjectDashBoradInfoView from '@/widgets/project/dash-borad-info-view-portlet/dash-borad-info-view-portlet.vue';
import ProjectProjectStatusBar from '@/widgets/project/project-status-bar-portlet/project-status-bar-portlet.vue';
import ProductLifeGetRoadmaps from '@/widgets/product-life/get-roadmaps-portlet/get-roadmaps-portlet.vue';
import TaskToolbar from '@/widgets/task/toolbar-portlet/toolbar-portlet.vue';
import TaskMainInfo from '@/widgets/task/main-info-portlet/main-info-portlet.vue';
import TaskWorkInfo from '@/widgets/task/work-info-portlet/work-info-portlet.vue';
import TaskMainDetail from '@/widgets/task/main-detail-portlet/main-detail-portlet.vue';
import TaskCurFinishedbyTask from '@/widgets/task/cur-finishedby-task-portlet/cur-finishedby-task-portlet.vue';
import TestSuiteCurSuitCaseGridView from '@/widgets/test-suite/cur-suit-case-grid-view-portlet/cur-suit-case-grid-view-portlet.vue';
import TestSuiteMainInfoView from '@/widgets/test-suite/main-info-view-portlet/main-info-view-portlet.vue';
import TestSuiteTestSuiteQuickAction from '@/widgets/test-suite/test-suite-quick-action-portlet/test-suite-quick-action-portlet.vue';
import TestTaskMainInfo from '@/widgets/test-task/main-info-portlet/main-info-portlet.vue';
import TestTaskToTestTestTask from '@/widgets/test-task/to-test-test-task-portlet/to-test-test-task-portlet.vue';
import TestTaskActionBar from '@/widgets/test-task/action-bar-portlet/action-bar-portlet.vue';
import TestTaskMainDetail from '@/widgets/test-task/main-detail-portlet/main-detail-portlet.vue';
import SysUpdateLogLastUpdate from '@/widgets/sys-update-log/last-update-portlet/last-update-portlet.vue';
import DocKeywords from '@/widgets/doc/keywords-portlet/keywords-portlet.vue';
import DocBasic from '@/widgets/doc/basic-portlet/basic-portlet.vue';
import DocMyFavourite from '@/widgets/doc/my-favourite-portlet/my-favourite-portlet.vue';
import DocMyDoc from '@/widgets/doc/my-doc-portlet/my-doc-portlet.vue';
import DocDocAction from '@/widgets/doc/doc-action-portlet/doc-action-portlet.vue';
import DocDocSum from '@/widgets/doc/doc-sum-portlet/doc-sum-portlet.vue';
import DocDOCSTATUS from '@/widgets/doc/docstatus-portlet/docstatus-portlet.vue';
import DocRecentUpdate from '@/widgets/doc/recent-update-portlet/recent-update-portlet.vue';
import DocMainBody from '@/widgets/doc/main-body-portlet/main-body-portlet.vue';
import BugBugSeverity from '@/widgets/bug/bug-severity-portlet/bug-severity-portlet.vue';
import BugBugSeverity_Project from '@/widgets/bug/bug-severity-project-portlet/bug-severity-project-portlet.vue';
import BugBugOpenedBy from '@/widgets/bug/bug-opened-by-portlet/bug-opened-by-portlet.vue';
import BugBugOpenedBy_Project from '@/widgets/bug/bug-opened-by-project-portlet/bug-opened-by-project-portlet.vue';
import BugBugModule from '@/widgets/bug/bug-module-portlet/bug-module-portlet.vue';
import BugBugModule_Project from '@/widgets/bug/bug-module-project-portlet/bug-module-project-portlet.vue';
import BugBugStatus from '@/widgets/bug/bug-status-portlet/bug-status-portlet.vue';
import BugBugStatus_Project from '@/widgets/bug/bug-status-project-portlet/bug-status-project-portlet.vue';
import BugDashboardBugLife from '@/widgets/bug/dashboard-bug-life-portlet/dashboard-bug-life-portlet.vue';
import BugBugType from '@/widgets/bug/bug-type-portlet/bug-type-portlet.vue';
import BugBugType_Project from '@/widgets/bug/bug-type-project-portlet/bug-type-project-portlet.vue';
import BugBugResolution from '@/widgets/bug/bug-resolution-portlet/bug-resolution-portlet.vue';
import BugBugResolution_Project from '@/widgets/bug/bug-resolution-project-portlet/bug-resolution-project-portlet.vue';
import BugBugResolvedBy from '@/widgets/bug/bug-resolved-by-portlet/bug-resolved-by-portlet.vue';
import BugBugResolvedBy_Project from '@/widgets/bug/bug-resolved-by-project-portlet/bug-resolved-by-project-portlet.vue';
import BugActionHistoryList from '@/widgets/bug/action-history-list-portlet/action-history-list-portlet.vue';
import BugDashboardBugMain from '@/widgets/bug/dashboard-bug-main-portlet/dashboard-bug-main-portlet.vue';
import BugBugDashboardActions from '@/widgets/bug/bug-dashboard-actions-portlet/bug-dashboard-actions-portlet.vue';
import BugTotalCurOpenedBug from '@/widgets/bug/total-cur-opened-bug-portlet/total-cur-opened-bug-portlet.vue';
import BugCurUserResolveBug from '@/widgets/bug/cur-user-resolve-bug-portlet/cur-user-resolve-bug-portlet.vue';
import BugStepsInfo from '@/widgets/bug/steps-info-portlet/steps-info-portlet.vue';
import IbzCaseCaseMain from '@/widgets/ibz-case/case-main-portlet/case-main-portlet.vue';
import IbzCaseCaseNewEdit from '@/widgets/ibz-case/case-new-edit-portlet/case-new-edit-portlet.vue';
import IbzCaseCaseInfo from '@/widgets/ibz-case/case-info-portlet/case-info-portlet.vue';
import IbzCaseIbzCases from '@/widgets/ibz-case/ibz-cases-portlet/ibz-cases-portlet.vue';
import SysEmployeePersonInfo from '@/widgets/sys-employee/person-info-portlet/person-info-portlet.vue';
import SysEmployeePersonBasicInformation from '@/widgets/sys-employee/person-basic-information-portlet/person-basic-information-portlet.vue';
import ActionActionHistory from '@/widgets/action/action-history-portlet/action-history-portlet.vue';
import ActionProjectTrendsTimeline from '@/widgets/action/project-trends-timeline-portlet/project-trends-timeline-portlet.vue';
import ActionProductTrendsTimeline from '@/widgets/action/product-trends-timeline-portlet/product-trends-timeline-portlet.vue';

export const  PortletComponent = {
    install(v: any, opt: any) {
        v.component('app-product-product-exp-view-portlet', ProductProductExpView);
        v.component('app-action-all-trends-portlet', ActionAllTrends);
        v.component('app-my-work-portlet', MyWork);
        v.component('app-bug-assigned-to-me-bug-portlet', BugAssignedToMeBug);
        v.component('app-task-assign-to-me-portlet', TaskAssignToMe);
        v.component('app-sys-update-log-last-update-portlet', SysUpdateLogLastUpdate);
        v.component('app-product-text-exp-view-portlet', ProductTextExpView);
        v.component('app-project-project-exp-view-portlet', ProjectProjectExpView);
        v.component('app-story-storyspec-portlet', StoryStoryspec);
        v.component('app-action-action-history-portlet', ActionActionHistory);
        v.component('app-story-main-toolbar-portlet', StoryMainToolbar);
        v.component('app-story-base-info-portlet', StoryBaseInfo);
        v.component('app-story-story-related-portlet', StoryStoryRelated);
        v.component('app-bug-steps-info-portlet', BugStepsInfo);
        v.component('app-bug-action-history-list-portlet', BugActionHistoryList);
        v.component('app-bug-bug-dashboard-actions-portlet', BugBugDashboardActions);
        v.component('app-bug-dashboard-bug-main-portlet', BugDashboardBugMain);
        v.component('app-bug-dashboard-bug-life-portlet', BugDashboardBugLife);
        v.component('app-doc-recent-update-portlet', DocRecentUpdate);
        v.component('app-doc-my-doc-portlet', DocMyDoc);
        v.component('app-doc-my-favourite-portlet', DocMyFavourite);
        v.component('app-doc-docstatus-portlet', DocDOCSTATUS);
        v.component('app-project-undone-project-portlet', ProjectUndoneProject);
        v.component('app-test-suite-cur-suit-case-grid-view-portlet', TestSuiteCurSuitCaseGridView);
        v.component('app-test-suite-test-suite-quick-action-portlet', TestSuiteTestSuiteQuickAction);
        v.component('app-test-suite-main-info-view-portlet', TestSuiteMainInfoView);
        v.component('app-ibz-case-case-main-portlet', IbzCaseCaseMain);
        v.component('app-ibz-case-ibz-cases-portlet', IbzCaseIbzCases);
        v.component('app-ibz-case-case-info-portlet', IbzCaseCaseInfo);
        v.component('app-ibz-case-case-new-edit-portlet', IbzCaseCaseNewEdit);
        v.component('app-project-un-closed-project-portlet', ProjectUnClosedProject);
        v.component('app-project-project-status-bar-portlet', ProjectProjectStatusBar);
        v.component('app-product-un-closed-product-portlet', ProductUnClosedProduct);
        v.component('app-product-product-status-chart-portlet', ProductProductStatusChart);
        v.component('app-story-assigned-to-me-story-portlet', StoryAssignedToMeStory);
        v.component('app-task-cur-finishedby-task-portlet', TaskCurFinishedbyTask);
        v.component('app-bug-cur-user-resolve-bug-portlet', BugCurUserResolveBug);
        v.component('app-user-year-work-stats-finish-task-and-bug-portlet', UserYearWorkStatsFinishTaskAndBug);
        v.component('app-test-task-main-detail-portlet', TestTaskMainDetail);
        v.component('app-test-task-action-bar-portlet', TestTaskActionBar);
        v.component('app-test-task-main-info-portlet', TestTaskMainInfo);
        v.component('app-task-main-detail-portlet', TaskMainDetail);
        v.component('app-task-toolbar-portlet', TaskToolbar);
        v.component('app-task-main-info-portlet', TaskMainInfo);
        v.component('app-task-work-info-portlet', TaskWorkInfo);
        v.component('app-case-case-result-portlet', CaseCaseResult);
        v.component('app-case-case-type-portlet', CaseCaseType);
        v.component('app-case-case-module-portlet', CaseCaseModule);
        v.component('app-case-case-lastrunner-portlet', CaseCaseLastrunner);
        v.component('app-bug-bug-severity-portlet', BugBugSeverity);
        v.component('app-bug-bug-type-portlet', BugBugType);
        v.component('app-bug-bug-status-portlet', BugBugStatus);
        v.component('app-bug-bug-resolution-portlet', BugBugResolution);
        v.component('app-bug-bug-opened-by-portlet', BugBugOpenedBy);
        v.component('app-bug-bug-module-portlet', BugBugModule);
        v.component('app-bug-bug-resolved-by-portlet', BugBugResolvedBy);
        v.component('app-todo-todo-desc-portlet', TodoTodoDesc);
        v.component('app-todo-todoaction-portlet', TodoTodoaction);
        v.component('app-todo-todo-dashboard-actions-portlet', TodoTodoDashboardActions);
        v.component('app-todo-todo-base-portlet', TodoTodoBase);
        v.component('app-story-total-cur-opened-story-pri-portlet', StoryTotalCurOpenedStoryPri);
        v.component('app-story-total-cur-opened-story-stage-portlet', StoryTotalCurOpenedStoryStage);
        v.component('app-user-year-work-stats-month-opened-story-portlet', UserYearWorkStatsMonthOpenedStory);
        v.component('app-bug-total-cur-opened-bug-portlet', BugTotalCurOpenedBug);
        v.component('app-case-total-cur-opened-case-portlet', CaseTotalCurOpenedCase);
        v.component('app-user-year-work-stats-month-opened-bug-and-case-portlet', UserYearWorkStatsMonthOpenedBugAndCase);
        v.component('app-burn-burn-down-chart-portlet', BurnBurnDownChart);
        v.component('app-action-project-trends-timeline-portlet', ActionProjectTrendsTimeline);
        v.component('app-ibz-project-member-related-members-portlet', IbzProjectMemberRelatedMembers);
        v.component('app-project-project-main-toolbar-portlet', ProjectProjectMainToolbar);
        v.component('app-project-dash-borad-info-view-portlet', ProjectDashBoradInfoView);
        v.component('app-doc-main-body-portlet', DocMainBody);
        v.component('app-doc-doc-action-portlet', DocDocAction);
        v.component('app-doc-doc-sum-portlet', DocDocSum);
        v.component('app-doc-keywords-portlet', DocKeywords);
        v.component('app-doc-basic-portlet', DocBasic);
        v.component('app-ibz-lib-ibz-lib-main-portlet', IbzLibIbzLibMain);
        v.component('app-ibz-lib-ibz-lib-cz-portlet', IbzLibIbzLibCz);
        v.component('app-case-main-info-portlet', CaseMainInfo);
        v.component('app-case-test-dashboard-quick-action-portlet', CaseTestDashboardQuickAction);
        v.component('app-case-test-main-detail-portlet', CaseTestMainDetail);
        v.component('app-case-case-result-project-portlet', CaseCaseResultProject);
        v.component('app-case-case-type-project-portlet', CaseCaseTypeProject);
        v.component('app-case-case-module-project-portlet', CaseCaseModuleProject);
        v.component('app-case-case-lastrunner-project-portlet', CaseCaseLastrunnerProject);
        v.component('app-bug-bug-severity-project-portlet', BugBugSeverity_Project);
        v.component('app-bug-bug-type-project-portlet', BugBugType_Project);
        v.component('app-bug-bug-status-project-portlet', BugBugStatus_Project);
        v.component('app-bug-bug-resolution-project-portlet', BugBugResolution_Project);
        v.component('app-bug-bug-opened-by-project-portlet', BugBugOpenedBy_Project);
        v.component('app-bug-bug-module-project-portlet', BugBugModule_Project);
        v.component('app-bug-bug-resolved-by-project-portlet', BugBugResolvedBy_Project);
        v.component('app-test-task-to-test-test-task-portlet', TestTaskToTestTestTask);
        v.component('app-case-me-create-case-portlet', CaseMeCreateCase);
        v.component('app-ibz-report-my-report-portlet', IbzReportMyReport);
        v.component('app-todo-my-upcoming-portlet', TodoMyUpcoming);
        v.component('app-product-life-get-roadmaps-portlet', ProductLifeGetRoadmaps);
        v.component('app-action-product-trends-timeline-portlet', ActionProductTrendsTimeline);
        v.component('app-product-product-main-toolbar-portlet', ProductProductMainToolbar);
        v.component('app-product-product-info-portlet', ProductProductInfo);
        v.component('app-case-dashboard-quick-action-portlet', CaseDashboardQuickAction);
        v.component('app-case-main-detail-portlet', CaseMainDetail);
        v.component('app-sys-employee-person-basic-information-portlet', SysEmployeePersonBasicInformation);
        v.component('app-sys-employee-person-info-portlet', SysEmployeePersonInfo);
        v.component('case-test-main-detail-portlet', CaseTestMainDetail);
        v.component('case-main-detail-portlet', CaseMainDetail);
        v.component('case-case-lastrunner-portlet', CaseCaseLastrunner);
        v.component('case-case-lastrunner-project-portlet', CaseCaseLastrunnerProject);
        v.component('case-case-module-portlet', CaseCaseModule);
        v.component('case-case-module-project-portlet', CaseCaseModuleProject);
        v.component('case-case-type-portlet', CaseCaseType);
        v.component('case-case-type-project-portlet', CaseCaseTypeProject);
        v.component('case-case-result-portlet', CaseCaseResult);
        v.component('case-test-dashboard-quick-action-portlet', CaseTestDashboardQuickAction);
        v.component('case-dashboard-quick-action-portlet', CaseDashboardQuickAction);
        v.component('case-case-result-project-portlet', CaseCaseResultProject);
        v.component('case-main-info-portlet', CaseMainInfo);
        v.component('case-total-cur-opened-case-portlet', CaseTotalCurOpenedCase);
        v.component('product-product-main-toolbar-portlet', ProductProductMainToolbar);
        v.component('product-product-info-portlet', ProductProductInfo);
        v.component('product-un-closed-product-portlet', ProductUnClosedProduct);
        v.component('ibz-lib-ibz-lib-main-portlet', IbzLibIbzLibMain);
        v.component('ibz-lib-ibz-lib-cz-portlet', IbzLibIbzLibCz);
        v.component('burn-burn-down-chart-portlet', BurnBurnDownChart);
        v.component('ibz-report-my-report-portlet', IbzReportMyReport);
        v.component('ibz-project-member-related-members-portlet', IbzProjectMemberRelatedMembers);
        v.component('story-base-info-portlet', StoryBaseInfo);
        v.component('story-assigned-to-me-story-portlet', StoryAssignedToMeStory);
        v.component('story-total-cur-opened-story-stage-portlet', StoryTotalCurOpenedStoryStage);
        v.component('story-total-cur-opened-story-pri-portlet', StoryTotalCurOpenedStoryPri);
        v.component('story-main-toolbar-portlet', StoryMainToolbar);
        v.component('story-story-related-portlet', StoryStoryRelated);
        v.component('story-storyspec-portlet', StoryStoryspec);
        v.component('todo-todoaction-portlet', TodoTodoaction);
        v.component('todo-todo-base-portlet', TodoTodoBase);
        v.component('todo-todo-desc-portlet', TodoTodoDesc);
        v.component('todo-todo-dashboard-actions-portlet', TodoTodoDashboardActions);
        v.component('user-year-work-stats-month-opened-bug-and-case-portlet', UserYearWorkStatsMonthOpenedBugAndCase);
        v.component('user-year-work-stats-finish-task-and-bug-portlet', UserYearWorkStatsFinishTaskAndBug);
        v.component('user-year-work-stats-month-opened-story-portlet', UserYearWorkStatsMonthOpenedStory);
        v.component('project-un-closed-project-portlet', ProjectUnClosedProject);
        v.component('project-undone-project-portlet', ProjectUndoneProject);
        v.component('project-project-main-toolbar-portlet', ProjectProjectMainToolbar);
        v.component('project-dash-borad-info-view-portlet', ProjectDashBoradInfoView);
        v.component('project-project-status-bar-portlet', ProjectProjectStatusBar);
        v.component('product-life-get-roadmaps-portlet', ProductLifeGetRoadmaps);
        v.component('task-toolbar-portlet', TaskToolbar);
        v.component('task-main-info-portlet', TaskMainInfo);
        v.component('task-work-info-portlet', TaskWorkInfo);
        v.component('task-main-detail-portlet', TaskMainDetail);
        v.component('task-cur-finishedby-task-portlet', TaskCurFinishedbyTask);
        v.component('test-suite-cur-suit-case-grid-view-portlet', TestSuiteCurSuitCaseGridView);
        v.component('test-suite-main-info-view-portlet', TestSuiteMainInfoView);
        v.component('test-suite-test-suite-quick-action-portlet', TestSuiteTestSuiteQuickAction);
        v.component('test-task-main-info-portlet', TestTaskMainInfo);
        v.component('test-task-to-test-test-task-portlet', TestTaskToTestTestTask);
        v.component('test-task-action-bar-portlet', TestTaskActionBar);
        v.component('test-task-main-detail-portlet', TestTaskMainDetail);
        v.component('sys-update-log-last-update-portlet', SysUpdateLogLastUpdate);
        v.component('doc-keywords-portlet', DocKeywords);
        v.component('doc-basic-portlet', DocBasic);
        v.component('doc-my-favourite-portlet', DocMyFavourite);
        v.component('doc-my-doc-portlet', DocMyDoc);
        v.component('doc-doc-action-portlet', DocDocAction);
        v.component('doc-doc-sum-portlet', DocDocSum);
        v.component('doc-docstatus-portlet', DocDOCSTATUS);
        v.component('doc-recent-update-portlet', DocRecentUpdate);
        v.component('doc-main-body-portlet', DocMainBody);
        v.component('bug-bug-severity-portlet', BugBugSeverity);
        v.component('bug-bug-severity-project-portlet', BugBugSeverity_Project);
        v.component('bug-bug-opened-by-portlet', BugBugOpenedBy);
        v.component('bug-bug-opened-by-project-portlet', BugBugOpenedBy_Project);
        v.component('bug-bug-module-portlet', BugBugModule);
        v.component('bug-bug-module-project-portlet', BugBugModule_Project);
        v.component('bug-bug-status-portlet', BugBugStatus);
        v.component('bug-bug-status-project-portlet', BugBugStatus_Project);
        v.component('bug-dashboard-bug-life-portlet', BugDashboardBugLife);
        v.component('bug-bug-type-portlet', BugBugType);
        v.component('bug-bug-type-project-portlet', BugBugType_Project);
        v.component('bug-bug-resolution-portlet', BugBugResolution);
        v.component('bug-bug-resolution-project-portlet', BugBugResolution_Project);
        v.component('bug-bug-resolved-by-portlet', BugBugResolvedBy);
        v.component('bug-bug-resolved-by-project-portlet', BugBugResolvedBy_Project);
        v.component('bug-action-history-list-portlet', BugActionHistoryList);
        v.component('bug-dashboard-bug-main-portlet', BugDashboardBugMain);
        v.component('bug-bug-dashboard-actions-portlet', BugBugDashboardActions);
        v.component('bug-total-cur-opened-bug-portlet', BugTotalCurOpenedBug);
        v.component('bug-cur-user-resolve-bug-portlet', BugCurUserResolveBug);
        v.component('bug-steps-info-portlet', BugStepsInfo);
        v.component('ibz-case-case-main-portlet', IbzCaseCaseMain);
        v.component('ibz-case-case-new-edit-portlet', IbzCaseCaseNewEdit);
        v.component('ibz-case-case-info-portlet', IbzCaseCaseInfo);
        v.component('ibz-case-ibz-cases-portlet', IbzCaseIbzCases);
        v.component('sys-employee-person-info-portlet', SysEmployeePersonInfo);
        v.component('sys-employee-person-basic-information-portlet', SysEmployeePersonBasicInformation);
        v.component('action-action-history-portlet', ActionActionHistory);
        v.component('action-project-trends-timeline-portlet', ActionProjectTrendsTimeline);
        v.component('action-product-trends-timeline-portlet', ActionProductTrendsTimeline);
    }
};