package cn.ibizlab.pms.zentao.logic.buglogic.bugnfavorites;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Bug bugbugnfavoritesdefault;
global cn.ibizlab.pms.core.zentao.service.IBugService iBzSysBugDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[取消收藏]
rule "rawsqlcall1"
ruleflow-group "bugbugnfavoritesrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",bugbugnfavoritesdefault.get("id"));
    String strSql="delete from T_IBZ_FAVORITES where type = 'bug' and account = #{et.param0} and objectid = #{et.param1}";
    iBzSysBugDefaultService.execute(strSql,param);//SQL调用
    update(bugbugnfavoritesdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "bugbugnfavoritesbegin"
    when
    then
    end

