package cn.ibizlab.pms.zentao.logic.buglogic.getproducts;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Bug buggetproductsdefault;
global cn.ibizlab.pms.core.zentao.service.IBugService iBzSysBugDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取产品]
rule "rawsqlcall1"
ruleflow-group "buggetproductsrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",buggetproductsdefault.get("project"));
    String strSql="select t.product,t1.`name` as productname from zt_projectproduct t left join zt_product t1 on t1.id = t.product where t.project = #{et.param0} LIMIT 0,1";
    java.util.List<JSONObject> entities=iBzSysBugDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            buggetproductsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(buggetproductsdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "buggetproductsbegin"
    when
    then
    end

