package cn.ibizlab.pms.zentao.logic.buglogic.getmodulebranch;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Module buggetmodulebranchmodule;
global cn.ibizlab.pms.core.zentao.domain.Bug buggetmodulebranchdefault;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.zentao.service.IBugService iBzSysBugDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取模块详情]
rule "deaction1"
ruleflow-group "buggetmodulebranchdeaction1"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(moduleservice.get(buggetmodulebranchmodule.getId()),buggetmodulebranchmodule);
    update(buggetmodulebranchmodule);//更新fact中变量值
    update(buggetmodulebranchdefault);//更新fact中变量值
    end

//逻辑处理节点[设置模块参数]
rule "prepareparam1"
ruleflow-group "buggetmodulebranchprepareparam1"
    when
    then
    buggetmodulebranchmodule.set("id",buggetmodulebranchdefault.get("module"));
    update(buggetmodulebranchmodule);//更新fact中变量值
    update(buggetmodulebranchdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "buggetmodulebranchbegin"
    when
    then
    end

//逻辑处理节点[设置bug平台值]
rule "prepareparam2"
ruleflow-group "buggetmodulebranchprepareparam2"
    when
    then
    buggetmodulebranchdefault.set("branch",buggetmodulebranchmodule.get("branch"));
    update(buggetmodulebranchmodule);//更新fact中变量值
    update(buggetmodulebranchdefault);//更新fact中变量值
    end

