package cn.ibizlab.pms.zentao.logic.buildlogic.mobprojectbuildcounter;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Build buildmobprojectbuildcounterdefault;
global cn.ibizlab.pms.core.zentao.service.IBuildService iBzSysBuildDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "buildmobprojectbuildcounterbegin"
    when
    then
    end

//逻辑处理节点[获取完成的需求数]
rule "rawsqlcall1"
ruleflow-group "buildmobprojectbuildcounterrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",buildmobprojectbuildcounterdefault.get("id"));
    String strSql="select count(1) as stories  from zt_story t1 where t1.deleted = '0' and  FIND_IN_SET(t1.id,(select stories from zt_build where id = #{et.param0}))";
    java.util.List<JSONObject> entities=iBzSysBuildDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            buildmobprojectbuildcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(buildmobprojectbuildcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取产生的bug]
rule "rawsqlcall3"
ruleflow-group "buildmobprojectbuildcounterrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",buildmobprojectbuildcounterdefault.get("id"));
    String strSql="select count(1) as createbugcnt from zt_bug t1 where t1.deleted = '0' and Find_IN_SET(#{et.param0},(select openedbuild from zt_bug where id = t1.id))";
    java.util.List<JSONObject> entities=iBzSysBuildDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            buildmobprojectbuildcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(buildmobprojectbuildcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取解决的bug]
rule "rawsqlcall2"
ruleflow-group "buildmobprojectbuildcounterrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",buildmobprojectbuildcounterdefault.get("id"));
    String strSql="select count(1) as bugs from zt_bug t1 where  t1.deleted = '0'  and FIND_IN_SET(t1.id,(select bugs from zt_build where id = #{et.param0})) ";
    java.util.List<JSONObject> entities=iBzSysBuildDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            buildmobprojectbuildcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(buildmobprojectbuildcounterdefault);//更新fact中变量值
    end

