package cn.ibizlab.pms.zentao.logic.caselogic.casenfavorite;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Case casecasenfavoritedefault;
global cn.ibizlab.pms.core.ibiz.domain.IbzFavorites casecasenfavoriteibzfavorite;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[用例取消收藏]
rule "casenfavrite"
ruleflow-group "casecasenfavoritecasenfavrite"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",casecasenfavoritedefault.get("id"));
    String strSql="delete from T_IBZ_FAVORITES where type = 'case' and account = #{et.param0} and objectid = #{et.param1}";
    iBzSysCaseDefaultService.execute(strSql,param);//SQL调用
    update(casecasenfavoritedefault);//更新fact中变量值
    update(casecasenfavoriteibzfavorite);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "casecasenfavoritebegin"
    when
    then
    end

