package cn.ibizlab.pms.zentao.logic.caselogic.getbytesttask;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Case casegetbytesttaskdefault;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "casegetbytesttaskbegin"
    when
    then
    end

//逻辑处理节点[获取详情]
rule "deaction1"
ruleflow-group "casegetbytesttaskdeaction1"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(caseservice.get(casegetbytesttaskdefault.getId()),casegetbytesttaskdefault);
    update(casegetbytesttaskdefault);//更新fact中变量值
    end

