package cn.ibizlab.pms.zentao.logic.caselogic.unlinksuitecases;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Case caseunlinksuitecasesdefault;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "caseunlinksuitecasesbegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "caseunlinksuitecasesprepareparam1"
    when
    then
    caseunlinksuitecasesdefault.set("case",caseunlinksuitecasesdefault.get("id"));
    caseunlinksuitecasesdefault.set("id",caseunlinksuitecasesdefault.get("suite"));
    update(caseunlinksuitecasesdefault);//更新fact中变量值
    end

//逻辑处理节点[移除用例]
rule "deaction1"
ruleflow-group "caseunlinksuitecasesdeaction1"
    when
    then
    caseservice.unlinkSuiteCase(caseunlinksuitecasesdefault);
    update(caseunlinksuitecasesdefault);//更新fact中变量值
    end

