package cn.ibizlab.pms.zentao.logic.caselogic.getcasestepbyidversion;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Case casegetcasestepbyidversiondefault;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "casegetcasestepbyidversionbegin"
    when
    then
    end

//逻辑处理节点[获取用例步骤]
rule "rawsqlcall1"
ruleflow-group "casegetcasestepbyidversionrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",casegetcasestepbyidversiondefault.get("id"));
    param.put("param1",casegetcasestepbyidversiondefault.get("version"));
    String strSql="select concat('[', GROUP_CONCAT(t1.casestep),']') as casestep from (SELECT JSON_OBJECT('case', t1.`CASE`,'desc', t1.`DESC`,'expect', t1.`EXPECT`,'id', t1.`ID`,'parent', t1.`PARENT`,'type', t1.`TYPE`,'version', t1.`VERSION`) as casestep,t1.`case`,t1.version  FROM `zt_casestep` t1) t1 where t1.`case` = #{et.param0} and t1.version =#{et.param1} GROUP BY t1.`case`,t1.version";
    java.util.List<JSONObject> entities=iBzSysCaseDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            casegetcasestepbyidversiondefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(casegetcasestepbyidversiondefault);//更新fact中变量值
    end

