package cn.ibizlab.pms.zentao.logic.caselogic.huafavorite;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.Case casehuafavoritedefault;
global cn.ibizlab.pms.core.ibiz.domain.IbzFavorites casehuafavoriteibzfavorite;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[create]
rule "create"
ruleflow-group "casehuafavoritecreate"
    when
    then
    caseservice.create(casehuafavoritedefault);
    update(casehuafavoritedefault);//更新fact中变量值
    update(casehuafavoriteibzfavorite);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "casehuafavoritebegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "casehuafavoriteprepareparam1"
    when
    then
    casehuafavoriteibzfavorite.set("objectid",casehuafavoritedefault.get("id"));
    casehuafavoriteibzfavorite.set("account",curuser.getSessionParams().get("srfloginname"));
    casehuafavoriteibzfavorite.set("type","case");
    update(casehuafavoritedefault);//更新fact中变量值
    update(casehuafavoriteibzfavorite);//更新fact中变量值
    end

