package cn.ibizlab.pms.zentao.logic.caselogic.runcases;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Case caseruncasesdefault;
global cn.ibizlab.pms.core.zentao.domain.TestRun caseruncasestestrun;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[重置id]
rule "prepareparam1"
ruleflow-group "caseruncasesprepareparam1"
    when
    then
    caseruncasesdefault.set("id",caseruncasestestrun.get("id"));
    update(caseruncasesdefault);//更新fact中变量值
    update(caseruncasestestrun);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "rawsqlcall1"
ruleflow-group "caseruncasesrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",caseruncasesdefault.get("id"));
    param.put("param1",caseruncasesdefault.get("task"));
    String strSql="SELECT t1.`ASSIGNEDTO`, t1.`CASE`, t1.`ID`, t1.`LASTRUNDATE`, t1.`LASTRUNNER`, t1.`LASTRUNRESULT`, t1.`STATUS`, t1.`TASK`, t1.`VERSION` FROM `zt_testrun` t1  where t1.`CASE` = #{et.param0} AND t1.`task` = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysCaseDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            caseruncasestestrun.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(caseruncasesdefault);//更新fact中变量值
    update(caseruncasestestrun);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "caseruncasesbegin"
    when
    then
    end

//逻辑处理节点[执行测试]
rule "deaction1"
ruleflow-group "caseruncasesdeaction1"
    when
    then
    caseservice.runCase(caseruncasesdefault);
    update(caseruncasesdefault);//更新fact中变量值
    update(caseruncasestestrun);//更新fact中变量值
    end

