package cn.ibizlab.pms.zentao.logic.caselogic.testruncases;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Case casetestruncasesdefault;
global cn.ibizlab.pms.core.zentao.domain.TestRun casetestruncasestestrun;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "casetestruncasesbegin"
    when
    then
    end

//逻辑处理节点[重置id]
rule "prepareparam1"
ruleflow-group "casetestruncasesprepareparam1"
    when
    then
    casetestruncasesdefault.set("srfarray",casetestruncasesdefault.get("casestep"));
    casetestruncasesdefault.set("case",casetestruncasesdefault.get("id"));
    casetestruncasesdefault.set("version",casetestruncasesdefault.get("version"));
    casetestruncasesdefault.set("id",casetestruncasestestrun.get("id"));
    update(casetestruncasesdefault);//更新fact中变量值
    update(casetestruncasestestrun);//更新fact中变量值
    end

//逻辑处理节点[执行测试]
rule "deaction1"
ruleflow-group "casetestruncasesdeaction1"
    when
    then
    caseservice.testRunCase(casetestruncasesdefault);
    update(casetestruncasesdefault);//更新fact中变量值
    update(casetestruncasestestrun);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "rawsqlcall1"
ruleflow-group "casetestruncasesrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",casetestruncasesdefault.get("id"));
    param.put("param1",casetestruncasesdefault.get("task"));
    String strSql="SELECT t1.`ASSIGNEDTO`, t1.`CASE`, t1.`ID`, t1.`LASTRUNDATE`, t1.`LASTRUNNER`, t1.`LASTRUNRESULT`, t1.`STATUS`, t1.`TASK`, t1.`VERSION` FROM `zt_testrun` t1  where t1.`CASE` = #{et.param0} AND t1.`task` = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysCaseDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            casetestruncasestestrun.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(casetestruncasesdefault);//更新fact中变量值
    update(casetestruncasestestrun);//更新fact中变量值
    end

