package cn.ibizlab.pms.zentao.logic.caselogic.runcases;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Case caseruncasesdefault;
global cn.ibizlab.pms.core.zentao.service.ICaseService caseservice;
global cn.ibizlab.pms.core.zentao.service.ICaseService iBzSysCaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "caseruncasesbegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "caseruncasesprepareparam1"
    when
    then
    caseruncasesdefault.set("case",caseruncasesdefault.get("id"));
    caseruncasesdefault.set("version",caseruncasesdefault.get("version"));
    caseruncasesdefault.set("srfarray",caseruncasesdefault.get("casestep"));
    caseruncasesdefault.set("id","0");
    update(caseruncasesdefault);//更新fact中变量值
    end

//逻辑处理节点[执行测试]
rule "deaction1"
ruleflow-group "caseruncasesdeaction1"
    when
    then
    caseservice.runCase(caseruncasesdefault);
    update(caseruncasesdefault);//更新fact中变量值
    end

