package cn.ibizlab.pms.zentao.logic.doclogic.byversionupdatecontext;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Doc docbyversionupdatecontextdefault;
global cn.ibizlab.pms.core.zentao.service.IDocService iBzSysDocDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取正文信息]
rule "rawsqlcall1"
ruleflow-group "docbyversionupdatecontextrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",docbyversionupdatecontextdefault.get("version"));
    param.put("param1",docbyversionupdatecontextdefault.get("id"));
    String strSql="select t.`content` as content from zt_doccontent t where t.`version` = #{et.param0} and t.`doc` = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysDocDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            docbyversionupdatecontextdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(docbyversionupdatecontextdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "docbyversionupdatecontextbegin"
    when
    then
    end

