package cn.ibizlab.pms.zentao.logic.docliblogic.curuserisf;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.DocLib doclibcuruserisfdefault;
global cn.ibizlab.pms.core.zentao.service.IDocLibService iBzSysDoclibDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "doclibcuruserisfbegin"
    when
    then
    end

