package cn.ibizlab.pms.ibiz.logic.doclibmodulelogic.doclibmodulenfavorite;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.DocLibModule doclibmoduledoclibmodulenfavoritedefault;
global cn.ibizlab.pms.core.ibiz.service.IDocLibModuleService iBzSysDoclibmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[取消收藏]
rule "rawsqlcall1"
ruleflow-group "doclibmoduledoclibmodulenfavoriterawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",doclibmoduledoclibmodulenfavoritedefault.get("type"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",doclibmoduledoclibmodulenfavoritedefault.get("id"));
    String strSql="delete from T_IBZ_FAVORITES where type = #{et.param0} and account = #{et.param1} and objectid = #{et.param2}";
    iBzSysDoclibmoduleDefaultService.execute(strSql,param);//SQL调用
    update(doclibmoduledoclibmodulenfavoritedefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "doclibmoduledoclibmodulenfavoritebegin"
    when
    then
    end

