package cn.ibizlab.pms.ibiz.logic.doclibmodulelogic.doclibmodulefavorite;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.DocLibModule doclibmoduledoclibmodulefavoritedefault;
global cn.ibizlab.pms.core.ibiz.domain.IbzFavorites doclibmoduledoclibmodulefavoriteibz_favorites;
global cn.ibizlab.pms.core.ibiz.service.IIbzFavoritesService ibzfavoritesservice;
global cn.ibizlab.pms.core.ibiz.service.IDocLibModuleService iBzSysDoclibmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "doclibmoduledoclibmodulefavoritebegin"
    when
    then
    end

//逻辑处理节点[收藏]
rule "deaction1"
ruleflow-group "doclibmoduledoclibmodulefavoritedeaction1"
    when
    then
    ibzfavoritesservice.create(doclibmoduledoclibmodulefavoriteibz_favorites);
    update(doclibmoduledoclibmodulefavoritedefault);//更新fact中变量值
    update(doclibmoduledoclibmodulefavoriteibz_favorites);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "doclibmoduledoclibmodulefavoriteprepareparam1"
    when
    then
    doclibmoduledoclibmodulefavoriteibz_favorites.set("objectid",doclibmoduledoclibmodulefavoritedefault.get("id"));
    doclibmoduledoclibmodulefavoriteibz_favorites.set("type",doclibmoduledoclibmodulefavoritedefault.get("type"));
    doclibmoduledoclibmodulefavoriteibz_favorites.set("account",curuser.getSessionParams().get("srfloginname"));
    update(doclibmoduledoclibmodulefavoritedefault);//更新fact中变量值
    update(doclibmoduledoclibmodulefavoriteibz_favorites);//更新fact中变量值
    end

