package cn.ibizlab.pms.ibiz.logic.ibzlibmodulelogic.removemodule;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzLibModule ibzlibmoduleremovemoduledefault;
global cn.ibizlab.pms.core.zentao.domain.Module ibzlibmoduleremovemodulemodule;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.IIbzLibModuleService iBzSysIbzlibmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[模块删除]
rule "deaction1"
ruleflow-group "ibzlibmoduleremovemoduledeaction1"
    when
    then
    moduleservice.remove(ibzlibmoduleremovemodulemodule.getId());
    update(ibzlibmoduleremovemoduledefault);//更新fact中变量值
    update(ibzlibmoduleremovemodulemodule);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzlibmoduleremovemodulebegin"
    when
    then
    end

//逻辑处理节点[设置模块参数]
rule "prepareparam1"
ruleflow-group "ibzlibmoduleremovemoduleprepareparam1"
    when
    then
    ibzlibmoduleremovemodulemodule.set("id",ibzlibmoduleremovemoduledefault.get("id"));
    update(ibzlibmoduleremovemoduledefault);//更新fact中变量值
    update(ibzlibmoduleremovemodulemodule);//更新fact中变量值
    end

