package cn.ibizlab.pms.ibiz.logic.ibzlibmodulelogic.fixpath;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzLibModule ibzlibmodulefixpathdefault;
global cn.ibizlab.pms.core.zentao.domain.Module ibzlibmodulefixpathzt_module;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.IIbzLibModuleService iBzSysIbzlibmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzlibmodulefixpathbegin"
    when
    then
    end

//逻辑处理节点[执行重建模块路径行为]
rule "deaction1"
ruleflow-group "ibzlibmodulefixpathdeaction1"
    when
    then
    moduleservice.update(ibzlibmodulefixpathzt_module);
    update(ibzlibmodulefixpathdefault);//更新fact中变量值
    update(ibzlibmodulefixpathzt_module);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "ibzlibmodulefixpathprepareparam1"
    when
    then
    ibzlibmodulefixpathzt_module.set("branch",ibzlibmodulefixpathdefault.get("branch"));
    ibzlibmodulefixpathzt_module.set("collector",ibzlibmodulefixpathdefault.get("collector"));
    ibzlibmodulefixpathzt_module.set("grade",ibzlibmodulefixpathdefault.get("grade"));
    ibzlibmodulefixpathzt_module.set("id",ibzlibmodulefixpathdefault.get("id"));
    ibzlibmodulefixpathzt_module.set("name",ibzlibmodulefixpathdefault.get("name"));
    ibzlibmodulefixpathzt_module.set("order",ibzlibmodulefixpathdefault.get("order"));
    ibzlibmodulefixpathzt_module.set("parent",ibzlibmodulefixpathdefault.get("parent"));
    ibzlibmodulefixpathzt_module.set("root",ibzlibmodulefixpathdefault.get("root"));
    ibzlibmodulefixpathzt_module.set("ibizshort",ibzlibmodulefixpathdefault.get("ibizshort"));
    ibzlibmodulefixpathzt_module.set("type",ibzlibmodulefixpathdefault.get("type"));
    update(ibzlibmodulefixpathdefault);//更新fact中变量值
    update(ibzlibmodulefixpathzt_module);//更新fact中变量值
    end

