package cn.ibizlab.pms.ibiz.logic.ibzmyterritorylogic.mobmenucount;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzMyTerritory ibzmyterritorymobmenucountdefault;
global cn.ibizlab.pms.core.ibiz.service.IIbzMyTerritoryService ibzmyterritoryservice;
global cn.ibizlab.pms.core.ibiz.service.IIbzMyTerritoryService iBzSysIbzmyterritoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[计算我的收藏数]
rule "rawsqlcall3"
ruleflow-group "ibzmyterritorymobmenucountrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",ibzmyterritorymobmenucountdefault.get("myfavoritebugs"));
    param.put("param1",ibzmyterritorymobmenucountdefault.get("myfavoritebugs"));
    param.put("param2",ibzmyterritorymobmenucountdefault.get("myfavoritetasks"));
    param.put("param3",ibzmyterritorymobmenucountdefault.get("myfavoritetasks"));
    param.put("param4",ibzmyterritorymobmenucountdefault.get("myfavoritestorys"));
    param.put("param5",ibzmyterritorymobmenucountdefault.get("myfavoritestorys"));
    String strSql="select ((case when #{et.param0} is null then 0 else #{et.param1} end )+ (case when #{et.param2} is null then 0 else #{et.param3} end ) + (case when #{et.param4} is null then 0 else #{et.param5} end )) as MYFAVORITES from dual";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymobmenucountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

//逻辑处理节点[我的]
rule "deaction2"
ruleflow-group "ibzmyterritorymobmenucountdeaction2"
    when
    then
    ibzmyterritoryservice.myTerritoryCount(ibzmyterritorymobmenucountdefault);
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

//逻辑处理节点[项目数]
rule "rawsqlcall2"
ruleflow-group "ibzmyterritorymobmenucountrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    param.put("param3",curuser.getSessionParams().get("srfloginname"));
    param.put("param4",curuser.getSessionParams().get("srfloginname"));
    param.put("param5",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT 	count( t1.id ) as PROJECTS FROM 	zt_project t1  WHERE 	t1.deleted = '0'  	AND ( 	t1.acl = 'open'  	OR t1.OPENEDBY = #{et.param0}  	OR t1.pm = #{et.param1}  	OR t1.PO = #{et.param2}  	OR t1.RD =#{et.param3}	OR t1.QD = #{et.param4} 	OR ( 	t1.acl = 'private'  	AND t1.id IN ( SELECT t3.root FROM zt_team t3 WHERE t3.account = #{et.param5} AND t3.type = 'project' )  	)  	)";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymobmenucountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

//逻辑处理节点[计算我的]
rule "rawsqlcall4"
ruleflow-group "ibzmyterritorymobmenucountrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",ibzmyterritorymobmenucountdefault.get("mybugs"));
    param.put("param1",ibzmyterritorymobmenucountdefault.get("mybugs"));
    param.put("param2",ibzmyterritorymobmenucountdefault.get("mytasks"));
    param.put("param3",ibzmyterritorymobmenucountdefault.get("mytasks"));
    param.put("param4",ibzmyterritorymobmenucountdefault.get("mystorys"));
    param.put("param5",ibzmyterritorymobmenucountdefault.get("mystorys"));
    param.put("param6",ibzmyterritorymobmenucountdefault.get("mytodocnt"));
    param.put("param7",ibzmyterritorymobmenucountdefault.get("mytodocnt"));
    String strSql="select ((case when #{et.param0} is null then 0 else #{et.param1} end )+ (case when #{et.param2} is null then 0 else #{et.param3} end ) + (case when #{et.param4} is null then 0 else #{et.param5} end ) + (case when #{et.param6} is null then 0 else #{et.param7} end )) as MYTERRITORYCNT from dual";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymobmenucountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzmyterritorymobmenucountbegin"
    when
    then
    end

//逻辑处理节点[产品数]
rule "rawsqlcall1"
ruleflow-group "ibzmyterritorymobmenucountrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    param.put("param3",curuser.getSessionParams().get("srfloginname"));
    param.put("param4",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT 		count( t1.id ) AS PRODUCTS  	FROM 		zt_product t1  	WHERE 		t1.deleted = '0'  		AND ( 			t1.acl = 'open'  			OR t1.CREATEDBY =#{et.param0} 			OR t1.PO = #{et.param1} 			OR t1.RD = #{et.param2}  			OR t1.QD = #{et.param3}  			OR t1.id IN ( 			SELECT 				t.product  			FROM 				zt_projectproduct t  			WHERE 				t.project IN ( SELECT t3.root FROM zt_team t3 WHERE t3.account = #{et.param4} AND t3.type = 'project' )  			)  	)";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymobmenucountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

//逻辑处理节点[收藏]
rule "deaction1"
ruleflow-group "ibzmyterritorymobmenucountdeaction1"
    when
    then
    ibzmyterritoryservice.myFavoriteCount(ibzmyterritorymobmenucountdefault);
    update(ibzmyterritorymobmenucountdefault);//更新fact中变量值
    end

