package cn.ibizlab.pms.ibiz.logic.ibzmyterritorylogic.myfavoritecount;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzMyTerritory ibzmyterritorymyfavoritecountdefault;
global cn.ibizlab.pms.core.ibiz.service.IIbzMyTerritoryService iBzSysIbzmyterritoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzmyterritorymyfavoritecountbegin"
    when
    then
    end

//逻辑处理节点[我的收藏任务数]
rule "rawsqlcall3"
ruleflow-group "ibzmyterritorymyfavoritecountrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    String strSql="select count(t1.id) AS MYFAVORITETASKS from zt_task t1 where t1.deleted = '0' and t1.id in (select t.OBJECTID from T_IBZ_FAVORITES t where t.type = 'task' and t.account = #{et.param0})";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymyfavoritecountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymyfavoritecountdefault);//更新fact中变量值
    end

//逻辑处理节点[获取我的收藏需求数]
rule "rawsqlcall1"
ruleflow-group "ibzmyterritorymyfavoritecountrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    String strSql="select count(t1.id) AS MYFAVORITESTORYS from zt_story t1 where t1.deleted = '0' and t1.id in (select t.OBJECTID from T_IBZ_FAVORITES t where t.type = 'story' and t.account = #{et.param0})";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymyfavoritecountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymyfavoritecountdefault);//更新fact中变量值
    end

//逻辑处理节点[我的收藏bug数]
rule "rawsqlcall2"
ruleflow-group "ibzmyterritorymyfavoritecountrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    String strSql="select count(t1.id) AS MYFAVORITEBUGS from zt_bug t1 where t1.deleted = '0' and t1.id in (select t.OBJECTID from T_IBZ_FAVORITES t where t.type = 'bug' and t.account = #{et.param0})";
    java.util.List<JSONObject> entities=iBzSysIbzmyterritoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzmyterritorymyfavoritecountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzmyterritorymyfavoritecountdefault);//更新fact中变量值
    end

