package cn.ibizlab.pms.ibiz.logic.ibzmyterritorylogic.mobmenucount;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.ibiz.domain.IbzMyTerritory ibzmyterritorymobmenucountdefault;
global cn.ibizlab.pms.core.ibiz.service.IIbzMyTerritoryService iBzSysIbzmyterritoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzmyterritorymobmenucountbegin"
    when
    then
    end

