package cn.ibizlab.pms.ibizpro.logic.ibzprostorymodulelogic.fixpath;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibizpro.domain.IBZProStoryModule ibzprostorymodulefixpathdefault;
global cn.ibizlab.pms.core.zentao.domain.Module ibzprostorymodulefixpathzt_module;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibizpro.service.IIBZProStoryModuleService iBzSysIbzprostorymoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzprostorymodulefixpathbegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "ibzprostorymodulefixpathprepareparam1"
    when
    then
    ibzprostorymodulefixpathzt_module.set("collector",ibzprostorymodulefixpathdefault.get("collector"));
    ibzprostorymodulefixpathzt_module.set("grade",ibzprostorymodulefixpathdefault.get("grade"));
    ibzprostorymodulefixpathzt_module.set("id",ibzprostorymodulefixpathdefault.get("id"));
    ibzprostorymodulefixpathzt_module.set("name",ibzprostorymodulefixpathdefault.get("name"));
    ibzprostorymodulefixpathzt_module.set("parent",ibzprostorymodulefixpathdefault.get("parent"));
    ibzprostorymodulefixpathzt_module.set("root",ibzprostorymodulefixpathdefault.get("root"));
    ibzprostorymodulefixpathzt_module.set("ibizshort",ibzprostorymodulefixpathdefault.get("ibizshort"));
    ibzprostorymodulefixpathzt_module.set("type",ibzprostorymodulefixpathdefault.get("type"));
    update(ibzprostorymodulefixpathdefault);//更新fact中变量值
    update(ibzprostorymodulefixpathzt_module);//更新fact中变量值
    end

//逻辑处理节点[执行重建模块路径行为]
rule "deaction1"
ruleflow-group "ibzprostorymodulefixpathdeaction1"
    when
    then
    moduleservice.update(ibzprostorymodulefixpathzt_module);
    update(ibzprostorymodulefixpathdefault);//更新fact中变量值
    update(ibzprostorymodulefixpathzt_module);//更新fact中变量值
    end

