package cn.ibizlab.pms.report.logic.ibzreportlogic.reportireceived;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.report.domain.IbzReport ibzreportreportireceiveddefault;
global cn.ibizlab.pms.core.report.service.IIbzReportService iBzSysIbzreportDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取未读周报]
rule "rawsqlcall3"
ruleflow-group "ibzreportreportireceivedrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT COUNT(1) as weeklycnt FROM `t_ibz_weekly` t1 where (t1.REPORTTO = #{et.param0} or FIND_IN_SET(#{et.param1},t1.mailto)) and not EXISTS(select 1 from zt_action t11 where t11.OBJECTID = t1.ibz_weeklyid and t11.objectType = 'weekly' and t11.actor = #{et.param2} and t11.action = 'read') and t1.ISSUBMIT = '1'";
    java.util.List<JSONObject> entities=iBzSysIbzreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzreportreportireceiveddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzreportreportireceiveddefault);//更新fact中变量值
    end

//逻辑处理节点[统计我收到的汇报数（未读）]
rule "rawsqlcall4"
ruleflow-group "ibzreportreportireceivedrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT 	COUNT( 1 ) AS reportlycnt  FROM 	`t_ibz_reportly` t1  WHERE 	( 		t1.REPORTTO = #{et.param0}  	OR FIND_IN_SET(#{et.param1}, t1.mailto ))  	AND NOT EXISTS ( 	SELECT 		1  	FROM 		zt_action t11  	WHERE 		t11.OBJECTID = t1.IBZ_REPORTLYID 		AND t11.objectType = 'reportly'  		AND t11.actor = #{et.param2}  		AND t11.action = 'read'  	)  	AND t1.ISSUBMIT = '1'";
    java.util.List<JSONObject> entities=iBzSysIbzreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzreportreportireceiveddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzreportreportireceiveddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzreportreportireceivedbegin"
    when
    then
    end

//逻辑处理节点[统计我收到的日报数]
rule "rawsqlcall1"
ruleflow-group "ibzreportreportireceivedrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT COUNT(1) as dailycnt FROM `t_ibz_daily` t1 where (t1.REPORTTO = #{et.param0} or FIND_IN_SET(#{et.param1},t1.mailto)) and not EXISTS(select 1 from zt_action t11 where t11.OBJECTID = t1.ibz_dailyid and t11.objectType = 'daily' and t11.actor = #{et.param2} and t11.action = 'read') and t1.ISSUBMIT = '1'";
    java.util.List<JSONObject> entities=iBzSysIbzreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzreportreportireceiveddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzreportreportireceiveddefault);//更新fact中变量值
    end

//逻辑处理节点[统计我收到的月报数（未读）]
rule "rawsqlcall2"
ruleflow-group "ibzreportreportireceivedrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    param.put("param2",curuser.getSessionParams().get("srfloginname"));
    String strSql="SELECT 	COUNT( 1 ) AS monthlycnt  FROM 	`t_ibz_monthly` t1  WHERE 	( 		t1.REPORTTO = #{et.param0}  	OR FIND_IN_SET(#{et.param1}, t1.mailto ))  	AND NOT EXISTS ( 	SELECT 		1  	FROM 		zt_action t11  	WHERE 		t11.OBJECTID = t1.ibz_monthlyid  		AND t11.objectType = 'monthly'  		AND t11.actor = #{et.param2}  		AND t11.action = 'read'  	)  	AND t1.ISSUBMIT = '1'";
    java.util.List<JSONObject> entities=iBzSysIbzreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            ibzreportreportireceiveddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(ibzreportreportireceiveddefault);//更新fact中变量值
    end

