package cn.ibizlab.pms.report.logic.ibzweeklylogic.update__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.report.domain.IbzWeekly ibzweeklyupdate__msdenytemp;
global cn.ibizlab.pms.core.report.domain.IbzWeekly ibzweeklyupdate__msdenydefault;
global cn.ibizlab.pms.core.report.service.IIbzWeeklyService ibzweeklyservice;
global cn.ibizlab.pms.core.report.service.IIbzWeeklyService iBzSysIbzweeklyDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "ibzweeklyupdate__msdenypreparetemp"
    when
    then
    ibzweeklyupdate__msdenytemp.set("ibzweeklyid",ibzweeklyupdate__msdenydefault.get("ibzweeklyid"));
    update(ibzweeklyupdate__msdenytemp);//更新fact中变量值
    update(ibzweeklyupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未提交]拒绝[update]操作]
rule "denybynsubmit"
ruleflow-group "ibzweeklyupdate__msdenydenybynsubmit"
    when
    then
    update(ibzweeklyupdate__msdenytemp);//更新fact中变量值
    update(ibzweeklyupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "ibzweeklyupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(ibzweeklyservice.get(ibzweeklyupdate__msdenytemp.getIbzweeklyid()),ibzweeklyupdate__msdenytemp);
    update(ibzweeklyupdate__msdenytemp);//更新fact中变量值
    update(ibzweeklyupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzweeklyupdate__msdenybegin"
    when
    then
    end

