package cn.ibizlab.pms.report.logic.ibzweeklylogic.remove__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.report.domain.IbzWeekly ibzweeklyremove__msdenydefault;
global cn.ibizlab.pms.core.report.domain.IbzWeekly ibzweeklyremove__msdenytemp;
global cn.ibizlab.pms.core.report.service.IIbzWeeklyService ibzweeklyservice;
global cn.ibizlab.pms.core.report.service.IIbzWeeklyService iBzSysIbzweeklyDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "ibzweeklyremove__msdenypreparetemp"
    when
    then
    ibzweeklyremove__msdenytemp.set("ibzweeklyid",ibzweeklyremove__msdenydefault.get("ibzweeklyid"));
    update(ibzweeklyremove__msdenydefault);//更新fact中变量值
    update(ibzweeklyremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "ibzweeklyremove__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(ibzweeklyservice.get(ibzweeklyremove__msdenytemp.getIbzweeklyid()),ibzweeklyremove__msdenytemp);
    update(ibzweeklyremove__msdenydefault);//更新fact中变量值
    update(ibzweeklyremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未提交]拒绝[remove]操作]
rule "denybynsunbmit"
ruleflow-group "ibzweeklyremove__msdenydenybynsunbmit"
    when
    then
    update(ibzweeklyremove__msdenydefault);//更新fact中变量值
    update(ibzweeklyremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzweeklyremove__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已提交]拒绝[remove]操作]
rule "denybysubmit"
ruleflow-group "ibzweeklyremove__msdenydenybysubmit"
    when
    then
    update(ibzweeklyremove__msdenydefault);//更新fact中变量值
    update(ibzweeklyremove__msdenytemp);//更新fact中变量值
    end

