package cn.ibizlab.pms.zentao.logic.productlogic.mobproductcounter;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Product productmobproductcounterdefault;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[获取需求数]
rule "rawsqlcall2"
ruleflow-group "productmobproductcounterrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproductcounterdefault.get("id"));
    String strSql="select count(1) as DRAFTSTORYCNT from zt_story t where t.deleted = '0'  AND t.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproductcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproductcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取相关bug数]
rule "rawsqlcall1"
ruleflow-group "productmobproductcounterrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproductcounterdefault.get("id"));
    String strSql="select count(1) as RELATEDBUGCNT from zt_bug t where t.deleted = '0'  AND t.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproductcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproductcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productmobproductcounterbegin"
    when
    then
    end

