package cn.ibizlab.pms.ibiz.logic.productteamlogic.getuserrole;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.PRODUCTTEAM productteamgetuserroledefault;
global cn.ibizlab.pms.core.ibiz.service.IPRODUCTTEAMService iBzSysProductteamDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取角色成员]
rule "rawsqlcall1"
ruleflow-group "productteamgetuserrolerawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productteamgetuserroledefault.get("account"));
    String strSql="select t11.`name` as role,null as id from zt_user t1 left JOIN zt_group t11 on t1.role = t11.role where t1.account = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductteamDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productteamgetuserroledefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productteamgetuserroledefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productteamgetuserrolebegin"
    when
    then
    end

