package cn.ibizlab.pms.zentao.logic.productplanlogic.getbedinandend;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.ProductPlan productplangetbedinandenddefault;
global cn.ibizlab.pms.core.zentao.service.IProductPlanService iBzSysProductplanDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productplangetbedinandendbegin"
    when
    then
    end

//逻辑处理节点[getbeginend]
rule "rawsqlcall1"
ruleflow-group "productplangetbedinandendrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productplangetbedinandenddefault.get("begin"));
    param.put("param1",productplangetbedinandenddefault.get("begin"));
    param.put("param2",productplangetbedinandenddefault.get("end"));
    param.put("param3",productplangetbedinandenddefault.get("end"));
    String strSql="select case when#{et.param0} = '2030-01-01' then ‘’ else #{et.param1} end as `BEGIN`, case when #{et.param2} = '2030-01-01' then '' else #{et.param3} end as `END` from dual";
    java.util.List<JSONObject> entities=iBzSysProductplanDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productplangetbedinandenddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productplangetbedinandenddefault);//更新fact中变量值
    end

