package cn.ibizlab.pms.zentao.logic.productplanlogic.mobproductplancounter;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.ProductPlan productplanmobproductplancounterdefault;
global cn.ibizlab.pms.core.zentao.service.IProductPlanService iBzSysProductplanDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productplanmobproductplancounterbegin"
    when
    then
    end

//逻辑处理节点[获取bug数]
rule "rawsqlcall2"
ruleflow-group "productplanmobproductplancounterrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",productplanmobproductplancounterdefault.get("id"));
    String strSql="select count(1) as bugcnt from zt_bug where deleted = '0' and plan = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductplanDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productplanmobproductplancounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productplanmobproductplancounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取需求数]
rule "rawsqlcall1"
ruleflow-group "productplanmobproductplancounterrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productplanmobproductplancounterdefault.get("id"));
    String strSql="select count(1) as storycnt from zt_story t1 where t1.deleted = '0' and t1.plan = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductplanDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productplanmobproductplancounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productplanmobproductplancounterdefault);//更新fact中变量值
    end

