package cn.ibizlab.pms.ibiz.logic.productmodulelogic.fixpath;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Module productmodulefixpathzt_module;
global cn.ibizlab.pms.core.ibiz.domain.ProductModule productmodulefixpathdefault;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.IProductModuleService iBzSysProductmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "productmodulefixpathprepareparam1"
    when
    then
    productmodulefixpathzt_module.set("branch",productmodulefixpathdefault.get("branch"));
    productmodulefixpathzt_module.set("collector",productmodulefixpathdefault.get("collector"));
    productmodulefixpathzt_module.set("grade",productmodulefixpathdefault.get("grade"));
    productmodulefixpathzt_module.set("id",productmodulefixpathdefault.get("id"));
    productmodulefixpathzt_module.set("name",productmodulefixpathdefault.get("name"));
    productmodulefixpathzt_module.set("order",productmodulefixpathdefault.get("order"));
    productmodulefixpathzt_module.set("parent",productmodulefixpathdefault.get("parent"));
    productmodulefixpathzt_module.set("root",productmodulefixpathdefault.get("root"));
    productmodulefixpathzt_module.set("ibizshort",productmodulefixpathdefault.get("ibizshort"));
    productmodulefixpathzt_module.set("type",productmodulefixpathdefault.get("type"));
    update(productmodulefixpathzt_module);//更新fact中变量值
    update(productmodulefixpathdefault);//更新fact中变量值
    end

//逻辑处理节点[执行重建模块路径行为]
rule "deaction1"
ruleflow-group "productmodulefixpathdeaction1"
    when
    then
    moduleservice.update(productmodulefixpathzt_module);
    update(productmodulefixpathzt_module);//更新fact中变量值
    update(productmodulefixpathdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productmodulefixpathbegin"
    when
    then
    end

