package cn.ibizlab.pms.zentao.logic.productlogic.cancelproducttop;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Product productcancelproducttopdefault;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productcancelproducttopbegin"
    when
    then
    end

//逻辑处理节点[删除置顶]
rule "rawsqlcall1"
ruleflow-group "productcancelproducttoprawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productcancelproducttopdefault.get("id"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    String strSql="delete from T_IBZ_TOP  where type = 'product' and objectid = #{et.param0} and account = #{et.param1}";
    iBzSysProductDefaultService.execute(strSql,param);//SQL调用
    update(productcancelproducttopdefault);//更新fact中变量值
    end

