package cn.ibizlab.pms.ibiz.logic.productteamlogic.getprojectdays;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Product productteamgetprojectdaysproduct;
global cn.ibizlab.pms.core.ibiz.domain.PRODUCTTEAM productteamgetprojectdaysdefault;
global cn.ibizlab.pms.core.zentao.service.IProductService productservice;
global cn.ibizlab.pms.core.ibiz.service.IPRODUCTTEAMService iBzSysProductteamDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取产品详情]
rule "deaction1"
ruleflow-group "productteamgetprojectdaysdeaction1"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(productservice.get(productteamgetprojectdaysproduct.getId()),productteamgetprojectdaysproduct);
    update(productteamgetprojectdaysproduct);//更新fact中变量值
    update(productteamgetprojectdaysdefault);//更新fact中变量值
    end

//逻辑处理节点[设置产品参数]
rule "prepareparam1"
ruleflow-group "productteamgetprojectdaysprepareparam1"
    when
    then
    productteamgetprojectdaysproduct.set("id",productteamgetprojectdaysdefault.get("root"));
    update(productteamgetprojectdaysproduct);//更新fact中变量值
    update(productteamgetprojectdaysdefault);//更新fact中变量值
    end

//逻辑处理节点[回填]
rule "prepareparam2"
ruleflow-group "productteamgetprojectdaysprepareparam2"
    when
    then
    productteamgetprojectdaysdefault.set("days",productteamgetprojectdaysproduct.get("id"));
    update(productteamgetprojectdaysproduct);//更新fact中变量值
    update(productteamgetprojectdaysdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productteamgetprojectdaysbegin"
    when
    then
    end

