package cn.ibizlab.pms.zentao.logic.productplanlogic.getoldplanname;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.ProductPlan productplangetoldplannamedefault;
global cn.ibizlab.pms.core.zentao.service.IProductPlanService iBzSysProductplanDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productplangetoldplannamebegin"
    when
    then
    end

//逻辑处理节点[获取名称]
rule "rawsqlcall1"
ruleflow-group "productplangetoldplannamerawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productplangetoldplannamedefault.get("product"));
    String strSql="select concat('(上次计划: ', t.`TITLE`, ')')  as oldtitle from zt_productplan t where t.product = #{et.param0} order by t.id desc LIMIT 0,1";
    java.util.List<JSONObject> entities=iBzSysProductplanDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productplangetoldplannamedefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productplangetoldplannamedefault);//更新fact中变量值
    end

