package cn.ibizlab.pms.zentao.logic.productlogic.mobproducttestcounter;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Product productmobproducttestcounterdefault;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productmobproducttestcounterbegin"
    when
    then
    end

//逻辑处理节点[套件数]
rule "rawsqlcall4"
ruleflow-group "productmobproducttestcounterrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproducttestcounterdefault.get("id"));
    String strSql="select count(t1.id) as TESTSUITECNT from ZT_TESTSUITE t1 where t1.deleted = '0' and t1.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproducttestcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproducttestcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取测试用例数]
rule "rawsqlcall2"
ruleflow-group "productmobproducttestcounterrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproducttestcounterdefault.get("id"));
    String strSql="select count(t1.id) as CASECNT from zt_case t1 where t1.deleted = '0' and t1.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproducttestcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproducttestcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[获取相关bug数]
rule "rawsqlcall1"
ruleflow-group "productmobproducttestcounterrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproducttestcounterdefault.get("id"));
    String strSql="select count(1) as RELATEDBUGCNT from zt_bug t where t.deleted = '0'  AND t.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproducttestcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproducttestcounterdefault);//更新fact中变量值
    end

//逻辑处理节点[测试单数]
rule "rawsqlcall3"
ruleflow-group "productmobproducttestcounterrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",productmobproducttestcounterdefault.get("id"));
    String strSql="select count(t1.id) as TESTTASKCNT from ZT_TESTTASK t1 where t1.deleted = '0' and t1.product = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productmobproducttestcounterdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productmobproducttestcounterdefault);//更新fact中变量值
    end

