package cn.ibizlab.pms.zentao.logic.productlogic.producttop;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzTop productproducttopibztop;
global cn.ibizlab.pms.core.zentao.domain.Product productproducttopdefault;
global cn.ibizlab.pms.core.ibiz.service.IIbzTopService ibztopservice;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取置顶最大排序值]
rule "rawsqlcall1"
ruleflow-group "productproducttoprawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    String strSql="select (case when max(t1.`objectorder`) >= 16000000  then max(t1.`objectorder`) + 1 else 16000000 end) as `objectorder` from T_IBZ_TOP t1 where t1.type = 'product' and t1.account= #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProductDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productproducttopibztop.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productproducttopibztop);//更新fact中变量值
    update(productproducttopdefault);//更新fact中变量值
    end

//逻辑处理节点[save置顶]
rule "deaction1"
ruleflow-group "productproducttopdeaction1"
    when
    then
    ibztopservice.create(productproducttopibztop);
    update(productproducttopibztop);//更新fact中变量值
    update(productproducttopdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productproducttopbegin"
    when
    then
    end

//逻辑处理节点[设置置顶数据]
rule "prepareparam1"
ruleflow-group "productproducttopprepareparam1"
    when
    then
    productproducttopibztop.set("objectid",productproducttopdefault.get("id"));
    productproducttopibztop.set("account",curuser.getSessionParams().get("srfloginname"));
    productproducttopibztop.set("type","product");
    update(productproducttopibztop);//更新fact中变量值
    update(productproducttopdefault);//更新fact中变量值
    end

