package cn.ibizlab.pms.zentao.logic.productlogic.update__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Product productupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Product productupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.IProductService productservice;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productupdate__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[关闭_已置顶]拒绝[update]操作]
rule "denybyclosed_1"
ruleflow-group "productupdate__msdenydenybyclosed_1"
    when
    then
    update(productupdate__msdenytemp);//更新fact中变量值
    update(productupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "productupdate__msdenypreparetemp"
    when
    then
    productupdate__msdenytemp.set("id",productupdate__msdenydefault.get("id"));
    update(productupdate__msdenytemp);//更新fact中变量值
    update(productupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "productupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(productservice.get(productupdate__msdenytemp.getId()),productupdate__msdenytemp);
    update(productupdate__msdenytemp);//更新fact中变量值
    update(productupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[正常_已置顶]拒绝[update]操作]
rule "denybynormal_1"
ruleflow-group "productupdate__msdenydenybynormal_1"
    when
    then
    update(productupdate__msdenytemp);//更新fact中变量值
    update(productupdate__msdenydefault);//更新fact中变量值
    end

