package cn.ibizlab.pms.ibiz.logic.productstatslogic.getcuruserbugcnt;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.ProductStats productstatsgetcuruserbugcntdefault;
global cn.ibizlab.pms.core.ibiz.service.IProductStatsService iBzSysProductstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productstatsgetcuruserbugcntbegin"
    when
    then
    end

//逻辑处理节点[获取bug数]
rule "rawsqlcall1"
ruleflow-group "productstatsgetcuruserbugcntrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",productstatsgetcuruserbugcntdefault.get("id"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    String strSql="select count(1) as Assigntomebugcnt from zt_bug t where t.deleted = '0' and t.product = #{et.param0} and t.assignedTo = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysProductstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            productstatsgetcuruserbugcntdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(productstatsgetcuruserbugcntdefault);//更新fact中变量值
    end

