package cn.ibizlab.pms.zentao.logic.productplanlogic.getbedinandend;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.ProductPlan productplangetbedinandenddefault;
global cn.ibizlab.pms.core.zentao.service.IProductPlanService iBzSysProductplanDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[设置待定]
rule "prepareparam1"
ruleflow-group "productplangetbedinandendprepareparam1"
    when
    then
    productplangetbedinandenddefault.set("begin",null);
    productplangetbedinandenddefault.set("end",null);
    update(productplangetbedinandenddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productplangetbedinandendbegin"
    when
    then
    end

