package cn.ibizlab.pms.zentao.logic.productlogic.producttop;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Product productproducttopdefault;
global cn.ibizlab.pms.core.zentao.service.IProductService iBzSysProductDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productproducttopbegin"
    when
    then
    end

