package cn.ibizlab.pms.zentao.logic.productplanlogic.getoldplanname;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.ProductPlan productplangetoldplannamedefault;
global cn.ibizlab.pms.core.zentao.service.IProductPlanService iBzSysProductplanDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "productplangetoldplannamebegin"
    when
    then
    end

