package cn.ibizlab.pms.zentao.logic.projectlogic.projecttop;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IbzTop projectprojecttopibztop;
global cn.ibizlab.pms.core.zentao.domain.Project projectprojecttopdefault;
global cn.ibizlab.pms.core.ibiz.service.IIbzTopService ibztopservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[设置参数]
rule "prepareparam1"
ruleflow-group "projectprojecttopprepareparam1"
    when
    then
    projectprojecttopibztop.set("objectid",projectprojecttopdefault.get("id"));
    projectprojecttopibztop.set("account",curuser.getSessionParams().get("srfloginname"));
    projectprojecttopibztop.set("type","project");
    update(projectprojecttopibztop);//更新fact中变量值
    update(projectprojecttopdefault);//更新fact中变量值
    end

//逻辑处理节点[获取置顶最大排序值]
rule "rawsqlcall1"
ruleflow-group "projectprojecttoprawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    String strSql="select (case when max(t1.`objectorder`) >= 16000000  then max(t1.`objectorder`) + 1 else 16000000 end) as `objectorder` from T_IBZ_TOP t1 where t1.type = 'project' and t1.account= #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectprojecttopibztop.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectprojecttopibztop);//更新fact中变量值
    update(projectprojecttopdefault);//更新fact中变量值
    end

//逻辑处理节点[save]
rule "deaction1"
ruleflow-group "projectprojecttopdeaction1"
    when
    then
    ibztopservice.create(projectprojecttopibztop);
    update(projectprojecttopibztop);//更新fact中变量值
    update(projectprojecttopdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectprojecttopbegin"
    when
    then
    end

