package cn.ibizlab.pms.zentao.logic.projectlogic.projecttaskqcnt;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.Project projectprojecttaskqcntdefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[已完成的任务数]
rule "rawsqlcall3"
ruleflow-group "projectprojecttaskqcntrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectprojecttaskqcntdefault.get("id"));
    String strSql="select count(t.id) as YCOMPLETETASKCNT from zt_task t where t.deleted = '0' and t.`status` = 'done' and t.project = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectprojecttaskqcntdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectprojecttaskqcntdefault);//更新fact中变量值
    end

//逻辑处理节点[我完成的任务数]
rule "rawsqlcall4"
ruleflow-group "projectprojecttaskqcntrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",projectprojecttaskqcntdefault.get("id"));
    String strSql="select count(t.id) as YCOMPLETETASKCNT from zt_task t where t.deleted = '0' and t.`finishedby` = #{et.param0} and t.project = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectprojecttaskqcntdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectprojecttaskqcntdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectprojecttaskqcntbegin"
    when
    then
    end

//逻辑处理节点[指派给我的任务数]
rule "rawsqlcall2"
ruleflow-group "projectprojecttaskqcntrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",curuser.getSessionParams().get("srfloginname"));
    param.put("param1",projectprojecttaskqcntdefault.get("id"));
    String strSql="select count(t.id) as ASSTOMYTASKCNT from zt_task t where t.deleted = '0' and t.assignedTo = #{et.param0} and t.project = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectprojecttaskqcntdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectprojecttaskqcntdefault);//更新fact中变量值
    end

//逻辑处理节点[未关闭任务数]
rule "rawsqlcall1"
ruleflow-group "projectprojecttaskqcntrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectprojecttaskqcntdefault.get("id"));
    String strSql="select count(t.id) as UNCLOSETASKCNT from zt_task t where t.deleted = '0' and t.`status` <> 'closed' and t.project = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectprojecttaskqcntdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectprojecttaskqcntdefault);//更新fact中变量值
    end

