package cn.ibizlab.pms.zentao.logic.projectlogic.getprojectproductplan;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Project projectgetprojectproductplandefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[获取产品计划]
rule "rawsfcode1"
ruleflow-group "projectgetprojectproductplanrawsfcode1"
    when
    then
    update(projectgetprojectproductplandefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectgetprojectproductplanbegin"
    when
    then
    end

