package cn.ibizlab.pms.zentao.logic.projectlogic.updateorder__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdateorder__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdateorder__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[状态[已关闭]拒绝[排序]操作]
rule "denybyclosed"
ruleflow-group "projectupdateorder__msdenydenybyclosed"
    when
    then
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未开始]拒绝[排序]操作]
rule "denybywait"
ruleflow-group "projectupdateorder__msdenydenybywait"
    when
    then
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectupdateorder__msdenypreparetemp"
    when
    then
    projectupdateorder__msdenytemp.set("id",projectupdateorder__msdenydefault.get("id"));
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectupdateorder__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectupdateorder__msdenytemp.getId()),projectupdateorder__msdenytemp);
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起]拒绝[排序]操作]
rule "denybysuspended"
ruleflow-group "projectupdateorder__msdenydenybysuspended"
    when
    then
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中]拒绝[排序]操作]
rule "denybydoing"
ruleflow-group "projectupdateorder__msdenydenybydoing"
    when
    then
    update(projectupdateorder__msdenydefault);//更新fact中变量值
    update(projectupdateorder__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectupdateorder__msdenybegin"
    when
    then
    end

