package cn.ibizlab.pms.ibiz.logic.projectmodulelogic.removemodule;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Module projectmoduleremovemodulemodule;
global cn.ibizlab.pms.core.ibiz.domain.ProjectModule projectmoduleremovemoduledefault;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.IProjectModuleService iBzSysProjectmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[模块删除]
rule "deaction1"
ruleflow-group "projectmoduleremovemoduledeaction1"
    when
    then
    moduleservice.remove(projectmoduleremovemodulemodule.getId());
    update(projectmoduleremovemodulemodule);//更新fact中变量值
    update(projectmoduleremovemoduledefault);//更新fact中变量值
    end

//逻辑处理节点[设置模块参数]
rule "prepareparam1"
ruleflow-group "projectmoduleremovemoduleprepareparam1"
    when
    then
    projectmoduleremovemodulemodule.set("id",projectmoduleremovemoduledefault.get("id"));
    update(projectmoduleremovemodulemodule);//更新fact中变量值
    update(projectmoduleremovemoduledefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectmoduleremovemodulebegin"
    when
    then
    end

