package cn.ibizlab.pms.zentao.logic.projectlogic.remove__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectremove__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Project projectremove__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectremove__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectremove__msdenytemp.getId()),projectremove__msdenytemp);
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectremove__msdenypreparetemp"
    when
    then
    projectremove__msdenytemp.set("id",projectremove__msdenydefault.get("id"));
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未开始_已置顶]拒绝[remove]操作]
rule "denybywait_1"
ruleflow-group "projectremove__msdenydenybywait_1"
    when
    then
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起_未置顶]拒绝[remove]操作]
rule "denybysuspended_0"
ruleflow-group "projectremove__msdenydenybysuspended_0"
    when
    then
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectremove__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已关闭_已置顶]拒绝[remove]操作]
rule "denybyclosed_1"
ruleflow-group "projectremove__msdenydenybyclosed_1"
    when
    then
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已置顶]拒绝[remove]操作]
rule "denybydoing_1"
ruleflow-group "projectremove__msdenydenybydoing_1"
    when
    then
    update(projectremove__msdenydefault);//更新fact中变量值
    update(projectremove__msdenytemp);//更新fact中变量值
    end

