package cn.ibizlab.pms.zentao.logic.projectlogic.getprojectproductplan;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectgetprojectproductplandefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取srfarray]
rule "rawsqlcall1"
ruleflow-group "projectgetprojectproductplanrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectgetprojectproductplandefault.get("id"));
    String strSql="select concat('[', GROUP_CONCAT(t1.srfarray),']') as srfarray  from ( select JSON_OBJECT('products', cast(product as char), 'branchs', cast(branch as char),'plans',cast(plan as char)) as srfarray,project from zt_projectproduct left join zt_product on id = product where project = #{et.param0} and deleted = '0') t1 GROUP BY t1.project";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectgetprojectproductplandefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectgetprojectproductplandefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectgetprojectproductplanbegin"
    when
    then
    end

