package cn.ibizlab.pms.zentao.logic.projectlogic.cancelprojecttop;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectcancelprojecttopdefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[删除置顶]
rule "rawsqlcall1"
ruleflow-group "projectcancelprojecttoprawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectcancelprojecttopdefault.get("id"));
    param.put("param1",curuser.getSessionParams().get("srfloginname"));
    String strSql="delete from T_IBZ_TOP  where type = 'project' and objectid = #{et.param0} and account = #{et.param1}";
    iBzSysProjectDefaultService.execute(strSql,param);//SQL调用
    update(projectcancelprojecttopdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectcancelprojecttopbegin"
    when
    then
    end

