package cn.ibizlab.pms.zentao.logic.projectlogic.updatecycle__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdatecycle__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdatecycle__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectupdatecycle__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectupdatecycle__msdenytemp.getId()),projectupdatecycle__msdenytemp);
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未开始]拒绝[根据结束日期更新可用工作日]操作]
rule "denybywait"
ruleflow-group "projectupdatecycle__msdenydenybywait"
    when
    then
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectupdatecycle__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已挂起]拒绝[根据结束日期更新可用工作日]操作]
rule "denybysuspended"
ruleflow-group "projectupdatecycle__msdenydenybysuspended"
    when
    then
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭]拒绝[根据结束日期更新可用工作日]操作]
rule "denybyclosed"
ruleflow-group "projectupdatecycle__msdenydenybyclosed"
    when
    then
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectupdatecycle__msdenypreparetemp"
    when
    then
    projectupdatecycle__msdenytemp.set("id",projectupdatecycle__msdenydefault.get("id"));
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中]拒绝[根据结束日期更新可用工作日]操作]
rule "denybydoing"
ruleflow-group "projectupdatecycle__msdenydenybydoing"
    when
    then
    update(projectupdatecycle__msdenytemp);//更新fact中变量值
    update(projectupdatecycle__msdenydefault);//更新fact中变量值
    end

