package cn.ibizlab.pms.ibiz.logic.projectteamlogic.getprojectdays;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.ProjectTeam projectteamgetprojectdaysdefault;
global cn.ibizlab.pms.core.ibiz.service.IProjectTeamService iBzSysProjectteamDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectteamgetprojectdaysbegin"
    when
    then
    end

