package cn.ibizlab.pms.zentao.logic.projectlogic.updatetempmajor__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdatetempmajor__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdatetempmajor__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[进行中_已置顶]拒绝[updatetempmajor]操作]
rule "denybydoing_1"
ruleflow-group "projectupdatetempmajor__msdenydenybydoing_1"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_未置顶]拒绝[updatetempmajor]操作]
rule "denybydoing_0"
ruleflow-group "projectupdatetempmajor__msdenydenybydoing_0"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectupdatetempmajor__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectupdatetempmajor__msdenypreparetemp"
    when
    then
    projectupdatetempmajor__msdenytemp.set("id",projectupdatetempmajor__msdenydefault.get("id"));
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未开始_已置顶]拒绝[updatetempmajor]操作]
rule "denybywait_1"
ruleflow-group "projectupdatetempmajor__msdenydenybywait_1"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_未置顶]拒绝[updatetempmajor]操作]
rule "denybyclosed_0"
ruleflow-group "projectupdatetempmajor__msdenydenybyclosed_0"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未开始_未置顶]拒绝[updatetempmajor]操作]
rule "denybywait_0"
ruleflow-group "projectupdatetempmajor__msdenydenybywait_0"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_已置顶]拒绝[updatetempmajor]操作]
rule "denybyclosed_1"
ruleflow-group "projectupdatetempmajor__msdenydenybyclosed_1"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectupdatetempmajor__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectupdatetempmajor__msdenytemp.getId()),projectupdatetempmajor__msdenytemp);
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起_未置顶]拒绝[updatetempmajor]操作]
rule "denybysuspended_0"
ruleflow-group "projectupdatetempmajor__msdenydenybysuspended_0"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起_已置顶]拒绝[updatetempmajor]操作]
rule "denybysuspended_1"
ruleflow-group "projectupdatetempmajor__msdenydenybysuspended_1"
    when
    then
    update(projectupdatetempmajor__msdenytemp);//更新fact中变量值
    update(projectupdatetempmajor__msdenydefault);//更新fact中变量值
    end

