package cn.ibizlab.pms.zentao.logic.projectlogic.update__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectupdate__msdenytemp.getId()),projectupdate__msdenytemp);
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectupdate__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectupdate__msdenypreparetemp"
    when
    then
    projectupdate__msdenytemp.set("id",projectupdate__msdenydefault.get("id"));
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起]拒绝[update]操作]
rule "denybysuspended"
ruleflow-group "projectupdate__msdenydenybysuspended"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

