package cn.ibizlab.pms.ibiz.logic.projectmodulelogic.fixpath;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Module projectmodulefixpathzt_module;
global cn.ibizlab.pms.core.ibiz.domain.ProjectModule projectmodulefixpathdefault;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.IProjectModuleService iBzSysProjectmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[执行重建模块路径行为]
rule "deaction1"
ruleflow-group "projectmodulefixpathdeaction1"
    when
    then
    moduleservice.fix(projectmodulefixpathzt_module);
    update(projectmodulefixpathzt_module);//更新fact中变量值
    update(projectmodulefixpathdefault);//更新fact中变量值
    end

//逻辑处理节点[转化至模块实体]
rule "prepareparam1"
ruleflow-group "projectmodulefixpathprepareparam1"
    when
    then
    update(projectmodulefixpathzt_module);//更新fact中变量值
    update(projectmodulefixpathdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectmodulefixpathbegin"
    when
    then
    end

