package cn.ibizlab.pms.zentao.logic.projectlogic.pmseeprojecttaskcount;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectpmseeprojecttaskcountdefault;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取所有任务]
rule "rawsqlcall4"
ruleflow-group "projectpmseeprojecttaskcountrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectpmseeprojecttaskcountdefault.get("srfcurproject"));
    String strSql="select count(*) as all from zt_task t1 where t1.deleted = '0' and t1.parent <= 0 and t1.project in (#{et.param0})";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectpmseeprojecttaskcountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectpmseeprojecttaskcountdefault);//更新fact中变量值
    end

//逻辑处理节点[获取周期任务]
rule "rawsqlcall2"
ruleflow-group "projectpmseeprojecttaskcountrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectpmseeprojecttaskcountdefault.get("srfcurproject"));
    String strSql="select count(*) as cycle  from zt_task t1 where t1.deleted = '0' and t1.parent <= 0 and t1.project in (#{et.param0}) and t1.taskspecies = 'cycle'";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectpmseeprojecttaskcountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectpmseeprojecttaskcountdefault);//更新fact中变量值
    end

//逻辑处理节点[获取计划任务]
rule "rawsqlcall3"
ruleflow-group "projectpmseeprojecttaskcountrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectpmseeprojecttaskcountdefault.get("srfcurproject"));
    String strSql="select count(*) as plan from zt_task t1 where t1.deleted = '0' and t1.parent <= 0 and t1.project in (#{et.param0}) and t1.taskspecies = 'plan'";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectpmseeprojecttaskcountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectpmseeprojecttaskcountdefault);//更新fact中变量值
    end

//逻辑处理节点[获取临时任务]
rule "rawsqlcall1"
ruleflow-group "projectpmseeprojecttaskcountrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",projectpmseeprojecttaskcountdefault.get("srfcurproject"));
    String strSql="select count(*) as temp  from zt_task t1 where t1.deleted = '0' and t1.parent <= 0 and t1.project in (#{et.param0}) and taskspecies = 'temp'";
    java.util.List<JSONObject> entities=iBzSysProjectDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            projectpmseeprojecttaskcountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(projectpmseeprojecttaskcountdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectpmseeprojecttaskcountbegin"
    when
    then
    end

