package cn.ibizlab.pms.zentao.logic.projectlogic.update__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Project projectupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IProjectService projectservice;
global cn.ibizlab.pms.core.zentao.service.IProjectService iBzSysProjectDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[未开始_已置顶]拒绝[update]操作]
rule "denybywait_1"
ruleflow-group "projectupdate__msdenydenybywait_1"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "projectupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(projectservice.get(projectupdate__msdenytemp.getId()),projectupdate__msdenytemp);
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "projectupdate__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "projectupdate__msdenypreparetemp"
    when
    then
    projectupdate__msdenytemp.set("id",projectupdate__msdenydefault.get("id"));
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起_已置顶]拒绝[update]操作]
rule "denybysuspended_1"
ruleflow-group "projectupdate__msdenydenybysuspended_1"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已挂起_未置顶]拒绝[update]操作]
rule "denybysuspended_0"
ruleflow-group "projectupdate__msdenydenybysuspended_0"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已置顶]拒绝[update]操作]
rule "denybydoing_1"
ruleflow-group "projectupdate__msdenydenybydoing_1"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_已置顶]拒绝[update]操作]
rule "denybyclosed_1"
ruleflow-group "projectupdate__msdenydenybyclosed_1"
    when
    then
    update(projectupdate__msdenydefault);//更新fact中变量值
    update(projectupdate__msdenytemp);//更新fact中变量值
    end

