package cn.ibizlab.pms.zentao.logic.releaselogic.update__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Release releaseupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Release releaseupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IReleaseService releaseservice;
global cn.ibizlab.pms.core.zentao.service.IReleaseService iBzSysReleaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[正常]拒绝[update]操作]
rule "denybynormal"
ruleflow-group "releaseupdate__msdenydenybynormal"
    when
    then
    update(releaseupdate__msdenydefault);//更新fact中变量值
    update(releaseupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "releaseupdate__msdenypreparetemp"
    when
    then
    releaseupdate__msdenytemp.set("id",releaseupdate__msdenydefault.get("id"));
    update(releaseupdate__msdenydefault);//更新fact中变量值
    update(releaseupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[停止维护]拒绝[update]操作]
rule "denybyterminate"
ruleflow-group "releaseupdate__msdenydenybyterminate"
    when
    then
    update(releaseupdate__msdenydefault);//更新fact中变量值
    update(releaseupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "releaseupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(releaseservice.get(releaseupdate__msdenytemp.getId()),releaseupdate__msdenytemp);
    update(releaseupdate__msdenydefault);//更新fact中变量值
    update(releaseupdate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "releaseupdate__msdenybegin"
    when
    then
    end

