package cn.ibizlab.pms.zentao.logic.releaselogic.remove__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Release releaseremove__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Release releaseremove__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.IReleaseService releaseservice;
global cn.ibizlab.pms.core.zentao.service.IReleaseService iBzSysReleaseDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[正常]拒绝[remove]操作]
rule "denybynormal"
ruleflow-group "releaseremove__msdenydenybynormal"
    when
    then
    update(releaseremove__msdenydefault);//更新fact中变量值
    update(releaseremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "releaseremove__msdenypreparetemp"
    when
    then
    releaseremove__msdenytemp.set("id",releaseremove__msdenydefault.get("id"));
    update(releaseremove__msdenydefault);//更新fact中变量值
    update(releaseremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[停止维护]拒绝[remove]操作]
rule "denybyterminate"
ruleflow-group "releaseremove__msdenydenybyterminate"
    when
    then
    update(releaseremove__msdenydefault);//更新fact中变量值
    update(releaseremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "releaseremove__msdenybegin"
    when
    then
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "releaseremove__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(releaseservice.get(releaseremove__msdenytemp.getId()),releaseremove__msdenytemp);
    update(releaseremove__msdenydefault);//更新fact中变量值
    update(releaseremove__msdenytemp);//更新fact中变量值
    end

