package cn.ibizlab.pms.zentao.logic.storylogic.getcuruserconcat;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Story storygetcuruserconcatdefault;
global cn.ibizlab.pms.core.zentao.service.IStoryService iBzSysStoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "storygetcuruserconcatbegin"
    when
    then
    end

//逻辑处理节点[获取联系人]
rule "rawsqlcall1"
ruleflow-group "storygetcuruserconcatrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",storygetcuruserconcatdefault.get("mailtoconact"));
    String strSql="select * from ibzemp t1 where find_in_set(t1.username,(select tt.userlist from zt_usercontact tt where tt.id = #{et.param0}))";
    java.util.List<JSONObject> entities=iBzSysStoryDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            storygetcuruserconcatdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(storygetcuruserconcatdefault);//更新fact中变量值
    end

