package cn.ibizlab.pms.zentao.logic.storylogic.buildunlinkstorys;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Story storybuildunlinkstorysdefault;
global cn.ibizlab.pms.core.zentao.service.IStoryService storyservice;
global cn.ibizlab.pms.core.zentao.service.IStoryService iBzSysStoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "storybuildunlinkstorysbegin"
    when
    then
    end

//逻辑处理节点[参数]
rule "prepareparam1"
ruleflow-group "storybuildunlinkstorysprepareparam1"
    when
    then
    storybuildunlinkstorysdefault.set("build",storybuildunlinkstorysdefault.get("build"));
    storybuildunlinkstorysdefault.set("id",storybuildunlinkstorysdefault.get("id"));
    update(storybuildunlinkstorysdefault);//更新fact中变量值
    end

//逻辑处理节点[处理]
rule "deaction1"
ruleflow-group "storybuildunlinkstorysdeaction1"
    when
    then
    storyservice.buildUnlinkStory(storybuildunlinkstorysdefault);
    update(storybuildunlinkstorysdefault);//更新fact中变量值
    end

