package cn.ibizlab.pms.zentao.logic.storylogic.sendnotice;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Story storysendnoticedefault;
global cn.ibizlab.pms.core.zentao.service.IStoryService iBzSysStoryDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "storysendnoticebegin"
    when
    then
    end

