package cn.ibizlab.pms.ibiz.logic.sysupdateloglogic.updatelasted;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.SysUpdateLog sysupdatelogupdatelasteddefault;
global cn.ibizlab.pms.core.ibiz.service.ISysUpdateLogService iBzSysSysupdatelogDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "sysupdatelogupdatelastedbegin"
    when
    then
    end

//逻辑处理节点[更新最新更新标识]
rule "rawsqlcall1"
ruleflow-group "sysupdatelogupdatelastedrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",sysupdatelogupdatelasteddefault.get("updatebranch"));
    param.put("param1",sysupdatelogupdatelasteddefault.get("sysupdatelogid"));
    param.put("param2",sysupdatelogupdatelasteddefault.get("latestupdate"));
    String strSql="update t_sys_update_log set LATESTUPDATE = 0 where LATESTUPDATE = 1 and UPDATEBRANCH = #{et.param0} and SYS_UPDATE_LOGID <> #{et.param1} and #{et.param2} = '1'";
    iBzSysSysupdatelogDefaultService.execute(strSql,param);//SQL调用
    update(sysupdatelogupdatelasteddefault);//更新fact中变量值
    end

