package cn.ibizlab.pms.zentao.logic.tasklogic.activate__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskactivate__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskactivate__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskactivate__msdenypreparetemp"
    when
    then
    taskactivate__msdenytemp.set("id",taskactivate__msdenydefault.get("id"));
    update(taskactivate__msdenydefault);//更新fact中变量值
    update(taskactivate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskactivate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskactivate__msdenytemp.getId()),taskactivate__msdenytemp);
    update(taskactivate__msdenydefault);//更新fact中变量值
    update(taskactivate__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskactivate__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已完成]拒绝[激活]操作]
rule "denybydone"
ruleflow-group "taskactivate__msdenydenybydone"
    when
    then
    update(taskactivate__msdenydefault);//更新fact中变量值
    update(taskactivate__msdenytemp);//更新fact中变量值
    end

