package cn.ibizlab.pms.zentao.logic.tasklogic.removetempmajor__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskremovetempmajor__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task taskremovetempmajor__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[状态[进行中]拒绝[removetempmajor]操作]
rule "denybydoing"
ruleflow-group "taskremovetempmajor__msdenydenybydoing"
    when
    then
    update(taskremovetempmajor__msdenytemp);//更新fact中变量值
    update(taskremovetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行]拒绝[removetempmajor]操作]
rule "denybywait"
ruleflow-group "taskremovetempmajor__msdenydenybywait"
    when
    then
    update(taskremovetempmajor__msdenytemp);//更新fact中变量值
    update(taskremovetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskremovetempmajor__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskremovetempmajor__msdenytemp.getId()),taskremovetempmajor__msdenytemp);
    update(taskremovetempmajor__msdenytemp);//更新fact中变量值
    update(taskremovetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskremovetempmajor__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskremovetempmajor__msdenypreparetemp"
    when
    then
    taskremovetempmajor__msdenytemp.set("id",taskremovetempmajor__msdenydefault.get("id"));
    update(taskremovetempmajor__msdenytemp);//更新fact中变量值
    update(taskremovetempmajor__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停]拒绝[removetempmajor]操作]
rule "denybypause"
ruleflow-group "taskremovetempmajor__msdenydenybypause"
    when
    then
    update(taskremovetempmajor__msdenytemp);//更新fact中变量值
    update(taskremovetempmajor__msdenydefault);//更新fact中变量值
    end

