package cn.ibizlab.pms.zentao.logic.tasklogic.updatestoryversion;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatestoryversiondefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdatestoryversionbegin"
    when
    then
    end

//逻辑处理节点[获取需求版本]
rule "rawsqlcall1"
ruleflow-group "taskupdatestoryversionrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",taskupdatestoryversiondefault.get("story"));
    String strSql="select version as STORYVERSION from zt_story where id = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysTaskDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            taskupdatestoryversiondefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(taskupdatestoryversiondefault);//更新fact中变量值
    end

//逻辑处理节点[重置需求版本]
rule "prepareparam1"
ruleflow-group "taskupdatestoryversionprepareparam1"
    when
    then
    taskupdatestoryversiondefault.set("storyversion","1");
    update(taskupdatestoryversiondefault);//更新fact中变量值
    end

