package cn.ibizlab.pms.zentao.logic.tasklogic.getuserconcat;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Task taskgetuserconcatdefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "taskgetuserconcatprepareparam1"
    when
    then
    taskgetuserconcatdefault.set("mailto",taskgetuserconcatdefault.get("mailtopk"));
    update(taskgetuserconcatdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskgetuserconcatbegin"
    when
    then
    end

