package cn.ibizlab.pms.zentao.logic.tasklogic.save__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task tasksave__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task tasksave__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "tasksave__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(tasksave__msdenytemp.getId()),tasksave__msdenytemp);
    update(tasksave__msdenytemp);//更新fact中变量值
    update(tasksave__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已完成]拒绝[save]操作]
rule "denybydone"
ruleflow-group "tasksave__msdenydenybydone"
    when
    then
    update(tasksave__msdenytemp);//更新fact中变量值
    update(tasksave__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "tasksave__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "tasksave__msdenypreparetemp"
    when
    then
    tasksave__msdenytemp.set("id",tasksave__msdenydefault.get("id"));
    update(tasksave__msdenytemp);//更新fact中变量值
    update(tasksave__msdenydefault);//更新fact中变量值
    end

