package cn.ibizlab.pms.zentao.logic.tasklogic.getprojectbyplan;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Task taskgetprojectbyplandefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskgetprojectbyplanbegin"
    when
    then
    end

//逻辑处理节点[根据需求获取项目]
rule "rawsqlcall1"
ruleflow-group "taskgetprojectbyplanrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",taskgetprojectbyplandefault.get("story"));
    String strSql="select t1.project,t11.`name` as projectname,t21.plan,t31.`TITLE` as PLANNAME  from zt_projectstory t1 inner join zt_project t11 on t1.project = t11.id INNER JOIN zt_story t21 on t1.story = t21.id left join zt_productplan t31 on t21.plan = t31.id  where t1.story = #{et.param0} LIMIT 0,1";
    java.util.List<JSONObject> entities=iBzSysTaskDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            taskgetprojectbyplandefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(taskgetprojectbyplandefault);//更新fact中变量值
    end

//逻辑处理节点[获取项目]
rule "rawsqlcall2"
ruleflow-group "taskgetprojectbyplanrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",taskgetprojectbyplandefault.get("plan"));
    String strSql="select t1.project,t11.`name` as projectname from zt_projectproduct t1 inner join zt_project t11 on t1.project = t11.id left join zt_productplan t21 on t21.product = t1.product where t21.id = #{et.param0} LIMIT 0,1";
    java.util.List<JSONObject> entities=iBzSysTaskDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            taskgetprojectbyplandefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(taskgetprojectbyplandefault);//更新fact中变量值
    end

//逻辑处理节点[设置常规参数]
rule "prepareparam1"
ruleflow-group "taskgetprojectbyplanprepareparam1"
    when
    then
    update(taskgetprojectbyplandefault);//更新fact中变量值
    end

