package cn.ibizlab.pms.zentao.logic.tasklogic.remove__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.Task taskremove__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskremove__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[已关闭_已收藏]拒绝[remove]操作]
rule "denybyclosed_1"
ruleflow-group "taskremove__msdenydenybyclosed_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskremove__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已暂停_已收藏]拒绝[remove]操作]
rule "denybypause_1"
ruleflow-group "taskremove__msdenydenybypause_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已收藏]拒绝[remove]操作]
rule "denybydoing_1"
ruleflow-group "taskremove__msdenydenybydoing_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行_已收藏]拒绝[remove]操作]
rule "denybywait_1"
ruleflow-group "taskremove__msdenydenybywait_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskremove__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskremove__msdenytemp.getId()),taskremove__msdenytemp);
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已取消_已收藏]拒绝[remove]操作]
rule "denybycancel_1"
ruleflow-group "taskremove__msdenydenybycancel_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已完成_已收藏]拒绝[remove]操作]
rule "denybydone_1"
ruleflow-group "taskremove__msdenydenybydone_1"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskremove__msdenypreparetemp"
    when
    then
    taskremove__msdenytemp.set("id",taskremove__msdenydefault.get("id"));
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

