package cn.ibizlab.pms.zentao.logic.tasklogic.updatetempmajor__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetempmajor__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetempmajor__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdatetempmajor__msdenybegin"
    when
    then
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskupdatetempmajor__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskupdatetempmajor__msdenytemp.getId()),taskupdatetempmajor__msdenytemp);
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中]拒绝[updatetempmajor]操作]
rule "denybydoing"
ruleflow-group "taskupdatetempmajor__msdenydenybydoing"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停]拒绝[updatetempmajor]操作]
rule "denybypause"
ruleflow-group "taskupdatetempmajor__msdenydenybypause"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行]拒绝[updatetempmajor]操作]
rule "denybywait"
ruleflow-group "taskupdatetempmajor__msdenydenybywait"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskupdatetempmajor__msdenypreparetemp"
    when
    then
    taskupdatetempmajor__msdenytemp.set("id",taskupdatetempmajor__msdenydefault.get("id"));
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

