package cn.ibizlab.pms.zentao.logic.tasklogic.remove__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskremove__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskremove__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskremove__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[未进行]拒绝[remove]操作]
rule "denybywait"
ruleflow-group "taskremove__msdenydenybywait"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskremove__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskremove__msdenytemp.getId()),taskremove__msdenytemp);
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停]拒绝[remove]操作]
rule "denybypause"
ruleflow-group "taskremove__msdenydenybypause"
    when
    then
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskremove__msdenypreparetemp"
    when
    then
    taskremove__msdenytemp.set("id",taskremove__msdenydefault.get("id"));
    update(taskremove__msdenydefault);//更新fact中变量值
    update(taskremove__msdenytemp);//更新fact中变量值
    end

