package cn.ibizlab.pms.zentao.logic.tasklogic.close__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskclose__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task taskclose__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[状态[已完成]拒绝[关闭]操作]
rule "denybydone"
ruleflow-group "taskclose__msdenydenybydone"
    when
    then
    update(taskclose__msdenytemp);//更新fact中变量值
    update(taskclose__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已取消]拒绝[关闭]操作]
rule "denybycancel"
ruleflow-group "taskclose__msdenydenybycancel"
    when
    then
    update(taskclose__msdenytemp);//更新fact中变量值
    update(taskclose__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskclose__msdenybegin"
    when
    then
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskclose__msdenypreparetemp"
    when
    then
    taskclose__msdenytemp.set("id",taskclose__msdenydefault.get("id"));
    update(taskclose__msdenytemp);//更新fact中变量值
    update(taskclose__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskclose__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskclose__msdenytemp.getId()),taskclose__msdenytemp);
    update(taskclose__msdenytemp);//更新fact中变量值
    update(taskclose__msdenydefault);//更新fact中变量值
    end

