package cn.ibizlab.pms.zentao.logic.tasklogic.updatetempmajor__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetempmajor__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetempmajor__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[状态[已取消_未收藏]拒绝[updatetempmajor]操作]
rule "denybycancel_0"
ruleflow-group "taskupdatetempmajor__msdenydenybycancel_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskupdatetempmajor__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskupdatetempmajor__msdenytemp.getId()),taskupdatetempmajor__msdenytemp);
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已取消_已收藏]拒绝[updatetempmajor]操作]
rule "denybycancel_1"
ruleflow-group "taskupdatetempmajor__msdenydenybycancel_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_未收藏]拒绝[updatetempmajor]操作]
rule "denybyclosed_0"
ruleflow-group "taskupdatetempmajor__msdenydenybyclosed_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_已收藏]拒绝[updatetempmajor]操作]
rule "denybyclosed_1"
ruleflow-group "taskupdatetempmajor__msdenydenybyclosed_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行_已收藏]拒绝[updatetempmajor]操作]
rule "denybywait_1"
ruleflow-group "taskupdatetempmajor__msdenydenybywait_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_未收藏]拒绝[updatetempmajor]操作]
rule "denybydoing_0"
ruleflow-group "taskupdatetempmajor__msdenydenybydoing_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行_未收藏]拒绝[updatetempmajor]操作]
rule "denybywait_0"
ruleflow-group "taskupdatetempmajor__msdenydenybywait_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已收藏]拒绝[updatetempmajor]操作]
rule "denybydoing_1"
ruleflow-group "taskupdatetempmajor__msdenydenybydoing_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskupdatetempmajor__msdenypreparetemp"
    when
    then
    taskupdatetempmajor__msdenytemp.set("id",taskupdatetempmajor__msdenydefault.get("id"));
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停_未收藏]拒绝[updatetempmajor]操作]
rule "denybypause_0"
ruleflow-group "taskupdatetempmajor__msdenydenybypause_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdatetempmajor__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已暂停_已收藏]拒绝[updatetempmajor]操作]
rule "denybypause_1"
ruleflow-group "taskupdatetempmajor__msdenydenybypause_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已完成_已收藏]拒绝[updatetempmajor]操作]
rule "denybydone_1"
ruleflow-group "taskupdatetempmajor__msdenydenybydone_1"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已完成_未收藏]拒绝[updatetempmajor]操作]
rule "denybydone_0"
ruleflow-group "taskupdatetempmajor__msdenydenybydone_0"
    when
    then
    update(taskupdatetempmajor__msdenydefault);//更新fact中变量值
    update(taskupdatetempmajor__msdenytemp);//更新fact中变量值
    end

