package cn.ibizlab.pms.zentao.logic.tasklogic.update__msdeny;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdate__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[未进行_已收藏]拒绝[update]操作]
rule "denybywait_1"
ruleflow-group "taskupdate__msdenydenybywait_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已收藏]拒绝[update]操作]
rule "denybydoing_1"
ruleflow-group "taskupdate__msdenydenybydoing_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskupdate__msdenytemp.getId()),taskupdate__msdenytemp);
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停_已收藏]拒绝[update]操作]
rule "denybypause_1"
ruleflow-group "taskupdate__msdenydenybypause_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已取消_已收藏]拒绝[update]操作]
rule "denybycancel_1"
ruleflow-group "taskupdate__msdenydenybycancel_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskupdate__msdenypreparetemp"
    when
    then
    taskupdate__msdenytemp.set("id",taskupdate__msdenydefault.get("id"));
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已完成_已收藏]拒绝[update]操作]
rule "denybydone_1"
ruleflow-group "taskupdate__msdenydenybydone_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_已收藏]拒绝[update]操作]
rule "denybyclosed_1"
ruleflow-group "taskupdate__msdenydenybyclosed_1"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

