package cn.ibizlab.pms.zentao.logic.tasklogic.getusernames;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Task taskgetusernamesdefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[项目团队]
rule "rawsqlcall2"
ruleflow-group "taskgetusernamesrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",taskgetusernamesdefault.get("project"));
    String strSql="select GROUP_CONCAT(tt.account separator ';') as USERNAMES from zt_team tt where tt.type = 'project' and tt.root = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysTaskDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            taskgetusernamesdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(taskgetusernamesdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskgetusernamesbegin"
    when
    then
    end

//逻辑处理节点[任务团队]
rule "rawsqlcall1"
ruleflow-group "taskgetusernamesrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",taskgetusernamesdefault.get("id"));
    String strSql="select GROUP_CONCAT(tt.account separator ';') as USERNAMES from zt_team tt where tt.type = 'task' and tt.root = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysTaskDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            taskgetusernamesdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(taskgetusernamesdefault);//更新fact中变量值
    end

