package cn.ibizlab.pms.zentao.logic.tasklogic.opentask;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskopentaskdefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskopentaskbegin"
    when
    then
    end

//逻辑处理节点[修改状态为开始]
rule "prepareparam1"
ruleflow-group "taskopentaskprepareparam1"
    when
    then
    taskopentaskdefault.set("status","doing");
    update(taskopentaskdefault);//更新fact中变量值
    end

