package cn.ibizlab.pms.zentao.logic.tasklogic.resettaskestimate;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Task taskresettaskestimatedefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskresettaskestimatebegin"
    when
    then
    end

//逻辑处理节点[重置工时统计]
rule "prepareparam1"
ruleflow-group "taskresettaskestimateprepareparam1"
    when
    then
    taskresettaskestimatedefault.set("taskestimate","null");
    update(taskresettaskestimatedefault);//更新fact中变量值
    end

