package cn.ibizlab.pms.zentao.logic.tasklogic.removetemp__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskremovetemp__msdenydefault;
global cn.ibizlab.pms.core.zentao.domain.Task taskremovetemp__msdenytemp;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[状态[未进行]拒绝[removetemp]操作]
rule "denybywait"
ruleflow-group "taskremovetemp__msdenydenybywait"
    when
    then
    update(taskremovetemp__msdenydefault);//更新fact中变量值
    update(taskremovetemp__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中]拒绝[removetemp]操作]
rule "denybydoing"
ruleflow-group "taskremovetemp__msdenydenybydoing"
    when
    then
    update(taskremovetemp__msdenydefault);//更新fact中变量值
    update(taskremovetemp__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskremovetemp__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskremovetemp__msdenytemp.getId()),taskremovetemp__msdenytemp);
    update(taskremovetemp__msdenydefault);//更新fact中变量值
    update(taskremovetemp__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskremovetemp__msdenypreparetemp"
    when
    then
    taskremovetemp__msdenytemp.set("id",taskremovetemp__msdenydefault.get("id"));
    update(taskremovetemp__msdenydefault);//更新fact中变量值
    update(taskremovetemp__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停]拒绝[removetemp]操作]
rule "denybypause"
ruleflow-group "taskremovetemp__msdenydenybypause"
    when
    then
    update(taskremovetemp__msdenydefault);//更新fact中变量值
    update(taskremovetemp__msdenytemp);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskremovetemp__msdenybegin"
    when
    then
    end

