package cn.ibizlab.pms.zentao.logic.tasklogic.updatetemp__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetemp__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdatetemp__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[状态[已完成_已收藏]拒绝[updatetemp]操作]
rule "denybydone_1"
ruleflow-group "taskupdatetemp__msdenydenybydone_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdatetemp__msdenybegin"
    when
    then
    end

//逻辑处理节点[状态[已暂停_已收藏]拒绝[updatetemp]操作]
rule "denybypause_1"
ruleflow-group "taskupdatetemp__msdenydenybypause_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[进行中_已收藏]拒绝[updatetemp]操作]
rule "denybydoing_1"
ruleflow-group "taskupdatetemp__msdenydenybydoing_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行_已收藏]拒绝[updatetemp]操作]
rule "denybywait_1"
ruleflow-group "taskupdatetemp__msdenydenybywait_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已取消_已收藏]拒绝[updatetemp]操作]
rule "denybycancel_1"
ruleflow-group "taskupdatetemp__msdenydenybycancel_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskupdatetemp__msdenypreparetemp"
    when
    then
    taskupdatetemp__msdenytemp.set("id",taskupdatetemp__msdenydefault.get("id"));
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已关闭_已收藏]拒绝[updatetemp]操作]
rule "denybyclosed_1"
ruleflow-group "taskupdatetemp__msdenydenybyclosed_1"
    when
    then
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskupdatetemp__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskupdatetemp__msdenytemp.getId()),taskupdatetemp__msdenytemp);
    update(taskupdatetemp__msdenytemp);//更新fact中变量值
    update(taskupdatetemp__msdenydefault);//更新fact中变量值
    end

