package cn.ibizlab.pms.zentao.logic.tasklogic.update__msdeny;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdate__msdenytemp;
global cn.ibizlab.pms.core.zentao.domain.Task taskupdate__msdenydefault;
global cn.ibizlab.pms.core.zentao.service.ITaskService taskservice;
global cn.ibizlab.pms.core.zentao.service.ITaskService iBzSysTaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "taskupdate__msdenybegin"
    when
    then
    end

//逻辑处理节点[获取数据]
rule "get"
ruleflow-group "taskupdate__msdenyget"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(taskservice.get(taskupdate__msdenytemp.getId()),taskupdate__msdenytemp);
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[未进行]拒绝[update]操作]
rule "denybywait"
ruleflow-group "taskupdate__msdenydenybywait"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[准备临时参数]
rule "preparetemp"
ruleflow-group "taskupdate__msdenypreparetemp"
    when
    then
    taskupdate__msdenytemp.set("id",taskupdate__msdenydefault.get("id"));
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

//逻辑处理节点[状态[已暂停]拒绝[update]操作]
rule "denybypause"
ruleflow-group "taskupdate__msdenydenybypause"
    when
    then
    update(taskupdate__msdenytemp);//更新fact中变量值
    update(taskupdate__msdenydefault);//更新fact中变量值
    end

