package cn.ibizlab.pms.zentao.logic.testreportlogic.getinfotesttasks;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.TestReport testreportgetinfotesttasksdefault;
global cn.ibizlab.pms.core.zentao.domain.TestTask testreportgetinfotesttaskstesttask;
global cn.ibizlab.pms.core.zentao.service.ITestReportService testreportservice;
global cn.ibizlab.pms.core.zentao.service.ITestReportService iBzSysTestreportDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取相应需求]
rule "rawsqlcall4"
ruleflow-group "testreportgetinfotesttasksrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("builds"));
    String strSql="select case when GROUP_CONCAT(t1.id) is null then '' else GROUP_CONCAT(t1.id) end as stories from ( select DISTINCT t1.* from zt_story t1  left join zt_build t11 on FIND_IN_SET(t1.id,t11.stories) where t1.deleted = '0' and  FIND_IN_SET(t11.id,#{et.param0}) ) t1 GROUP BY t1.product";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "testreportgetinfotesttasksprepareparam1"
    when
    then
    testreportgetinfotesttasksdefault.set("objectid",testreportgetinfotesttasksdefault.get("project"));
    testreportgetinfotesttasksdefault.set("objecttype","project");
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取产品]
rule "rawsqlcall7"
ruleflow-group "testreportgetinfotesttasksrawsqlcall7"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("tasks"));
    String strSql="select t.product  from (select DISTINCT t.product from zt_testtask t where t.deleted = '0' and FIND_IN_SET(t.id,#{et.param0})) t  LIMIT 0,1";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取影响bug]
rule "rawsqlcall5"
ruleflow-group "testreportgetinfotesttasksrawsqlcall5"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("product"));
    param.put("param1",testreportgetinfotesttasksdefault.get("begin"));
    param.put("param2",testreportgetinfotesttasksdefault.get("tasks"));
    param.put("param3",testreportgetinfotesttasksdefault.get("begin"));
    param.put("param4",testreportgetinfotesttasksdefault.get("end"));
    String strSql="select GROUP_CONCAT(t1.id) as bugs from zt_bug t1 where t1.deleted = '0' and t1.product = #{et.param0} and t1.RESOLUTION in('fixed','postponed') and t1.openedDate < #{et.param1} and (FIND_IN_SET(t1.id,(select GROUP_CONCAT(t2.bugs) from zt_build t2 where t2.id in (select build from zt_testtask t3 where t3.deleted = '0' and FIND_IN_SET(t3.id,#{et.param2})) ORDER BY t2.product)) or (t1.resolvedBuild = 'trunk' and t1.resolvedDate >= #{et.param3} and t1.resolvedDate <= CONCAT(#{et.param4},' 23:59:59'))) GROUP BY t1.product";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取项目周期]
rule "rawsqlcall3"
ruleflow-group "testreportgetinfotesttasksrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("project"));
    String strSql="select  t1.`begin`,t1.`end` , CONCAT_WS( ' ', DATE_FORMAT( now( ), '%Y-%m-%d' ), concat( 'PROJECT#', t1.id ), t1.`name`, '测试报告' ) AS TITLE,t1.name as projectname from zt_project t1 where t1.id = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取产品数]
rule "rawsqlcall6"
ruleflow-group "testreportgetinfotesttasksrawsqlcall6"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("tasks"));
    String strSql="select COUNT(1) as productcnt from ( select DISTINCT t.product from zt_testtask t where t.deleted = '0' and FIND_IN_SET(t.id,#{et.param0})) t";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取概况信息]
rule "deaction1"
ruleflow-group "testreportgetinfotesttasksdeaction1"
    when
    then
    testreportservice.getInfoTestTaskOvProject(testreportgetinfotesttasksdefault);
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "testreportgetinfotesttasksbegin"
    when
    then
    end

//逻辑处理节点[获取数据]
rule "rawsqlcall1"
ruleflow-group "testreportgetinfotesttasksrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("project"));
    param.put("param1",testreportgetinfotesttasksdefault.get("tasks"));
    String strSql="select case when GROUP_CONCAT(DISTINCT t1.`case` order by t1.`case` asc) is null then '' else GROUP_CONCAT(DISTINCT t1.`case` order by t1.`case` asc) end as cases,case when GROUP_CONCAT(DISTINCT t1.lastRunner) is null then '' else GROUP_CONCAT(DISTINCT t1.lastRunner) end  as MEMBERS	from (select t1.*,#{et.param0} as project from zt_testrun t1 left join zt_case t11 on t1.`case` = t11.id where t11.deleted = '0' and FIND_IN_SET(t1.task, #{et.param1})) t1 GROUP BY t1.project";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

//逻辑处理节点[获取测试单]
rule "rawsqlcall2"
ruleflow-group "testreportgetinfotesttasksrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",testreportgetinfotesttasksdefault.get("tasks"));
    String strSql="select case when GROUP_CONCAT(DISTINCT t1.build) is null then '' else GROUP_CONCAT(DISTINCT t1.build) end as builds  from zt_testtask t1 where FIND_IN_SET(t1.id, #{et.param0}) and t1.deleted = '0' GROUP BY t1.project";
    java.util.List<JSONObject> entities=iBzSysTestreportDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testreportgetinfotesttasksdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testreportgetinfotesttasksdefault);//更新fact中变量值
    update(testreportgetinfotesttaskstesttask);//更新fact中变量值
    end

