package cn.ibizlab.pms.zentao.logic.testreportlogic.getinfotesttask;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
global cn.ibizlab.pms.core.zentao.domain.TestReport testreportgetinfotesttaskdefault;
global cn.ibizlab.pms.core.zentao.domain.TestTask testreportgetinfotesttasktesttask;
global cn.ibizlab.pms.core.zentao.service.ITestReportService iBzSysTestreportDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "testreportgetinfotesttaskbegin"
    when
    then
    end

