package cn.ibizlab.pms.zentao.logic.testtasklogic.mobtesttaskcounter;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.TestTask testtaskmobtesttaskcounterdefault;
global cn.ibizlab.pms.core.zentao.service.ITestTaskService iBzSysTesttaskDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "testtaskmobtesttaskcounterbegin"
    when
    then
    end

