package cn.ibizlab.pms.ibiz.logic.testmodulelogic.removemodule;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Module testmoduleremovemodulemodule;
global cn.ibizlab.pms.core.ibiz.domain.TestModule testmoduleremovemoduledefault;
global cn.ibizlab.pms.core.zentao.service.IModuleService moduleservice;
global cn.ibizlab.pms.core.ibiz.service.ITestModuleService iBzSysTestmoduleDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "testmoduleremovemodulebegin"
    when
    then
    end

//逻辑处理节点[模块删除]
rule "deaction1"
ruleflow-group "testmoduleremovemoduledeaction1"
    when
    then
    moduleservice.remove(testmoduleremovemodulemodule.getId());
    update(testmoduleremovemodulemodule);//更新fact中变量值
    update(testmoduleremovemoduledefault);//更新fact中变量值
    end

//逻辑处理节点[设置模块参数]
rule "prepareparam1"
ruleflow-group "testmoduleremovemoduleprepareparam1"
    when
    then
    testmoduleremovemodulemodule.set("id",testmoduleremovemoduledefault.get("id"));
    update(testmoduleremovemodulemodule);//更新fact中变量值
    update(testmoduleremovemoduledefault);//更新fact中变量值
    end

