package cn.ibizlab.pms.zentao.logic.testsuitelogic.mobtestsuitecount;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.TestSuite testsuitemobtestsuitecountdefault;
global cn.ibizlab.pms.core.zentao.service.ITestSuiteService iBzSysTestsuiteDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "testsuitemobtestsuitecountbegin"
    when
    then
    end

//逻辑处理节点[查询测试用例数]
rule "rawsqlcall1"
ruleflow-group "testsuitemobtestsuitecountrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",testsuitemobtestsuitecountdefault.get("id"));
    String strSql="select count(t1.case) as CASECNT from ZT_SUITECASE t1 where t1.suite = #{et.param0}";
    java.util.List<JSONObject> entities=iBzSysTestsuiteDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            testsuitemobtestsuitecountdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(testsuitemobtestsuitecountdefault);//更新fact中变量值
    end

