package cn.ibizlab.pms.zentao.logic.todologic.resetbeginend;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Todo todoresetbeginenddefault;
global cn.ibizlab.pms.core.zentao.service.ITodoService iBzSysTodoDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "todoresetbeginendbegin"
    when
    then
    end

//逻辑处理节点[获取开始日期]
rule "rawsqlcall1"
ruleflow-group "todoresetbeginendrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",todoresetbeginenddefault.get("begin"));
    param.put("param1",todoresetbeginenddefault.get("begin"));
    param.put("param2",todoresetbeginenddefault.get("end"));
    param.put("param3",todoresetbeginenddefault.get("end"));
    String strSql="select (case when #{et.param0} = '2030-01-01' then null else #{et.param1} end) as `BEGIN`,(case when #{et.param2} = '2030-01-01' then null else #{et.param3} end) as `END` from dual";
    java.util.List<JSONObject> entities=iBzSysTodoDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            todoresetbeginenddefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(todoresetbeginenddefault);//更新fact中变量值
    end

