package cn.ibizlab.pms.zentao.logic.todologic.gettodotitle;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.zentao.domain.Todo todogettodotitledefault;
global cn.ibizlab.pms.core.zentao.service.ITodoService iBzSysTodoDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "todogettodotitlebegin"
    when
    then
    end

//逻辑处理节点[获取待办的标题]
rule "rawsqlcall1"
ruleflow-group "todogettodotitlerawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",todogettodotitledefault.get("idvalue"));
    param.put("param1",todogettodotitledefault.get("type"));
    String strSql="select t.`name` as `NAMe` from ( select t.TITLE AS `name`, t.id,'bug' as type from zt_bug t union select t.TITLE AS `name`,t.id,'story' as type from zt_story t union select t.`name`,t.id,'task' as type from zt_task t ) t where t.id = #{et.param0} and t.type = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysTodoDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            todogettodotitledefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(todogettodotitledefault);//更新fact中变量值
    end

