package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getinfo;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetinfodefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService useryearworkstatsservice;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetinfobegin"
    when
    then
    end

//逻辑处理节点[获取产品经理信息]
rule "deaction4"
ruleflow-group "useryearworkstatsgetinfodeaction4"
    when
    then
    useryearworkstatsservice.getPoInfomation(useryearworkstatsgetinfodefault);
    update(useryearworkstatsgetinfodefault);//更新fact中变量值
    end

//逻辑处理节点[获取研发用户信息]
rule "deaction2"
ruleflow-group "useryearworkstatsgetinfodeaction2"
    when
    then
    useryearworkstatsservice.getDevInfomation(useryearworkstatsgetinfodefault);
    update(useryearworkstatsgetinfodefault);//更新fact中变量值
    end

//逻辑处理节点[获取用户信息]
rule "deaction1"
ruleflow-group "useryearworkstatsgetinfodeaction1"
    when
    then
    cn.ibizlab.pms.util.helper.CachedBeanCopier.copy(useryearworkstatsservice.get(useryearworkstatsgetinfodefault.getId()),useryearworkstatsgetinfodefault);
    update(useryearworkstatsgetinfodefault);//更新fact中变量值
    end

//逻辑处理节点[获取测试用户信息]
rule "deaction3"
ruleflow-group "useryearworkstatsgetinfodeaction3"
    when
    then
    useryearworkstatsservice.getQaInfomation(useryearworkstatsgetinfodefault);
    update(useryearworkstatsgetinfodefault);//更新fact中变量值
    end

