package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getpoinfomation;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetpoinfomationdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取计划数]
rule "rawsqlcall2"
ruleflow-group "useryearworkstatsgetpoinfomationrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    param.put("param1",useryearworkstatsgetpoinfomationdefault.get("account"));
    String strSql="select count(1) as `yearplancnt` from zt_productplan t left join zt_action t2 on t2.objectID = t.id and t2.objectType = 'productplan' where LEFT(t2.date, 4) = #{et.param0} and t2.actor = #{et.param1} and t2.action = 'opened' and t.product <> 0";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetpoinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetpoinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取登录数]
rule "rawsqlcall4"
ruleflow-group "useryearworkstatsgetpoinfomationrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    String strSql="select count(1) as `YEARVISITS` from zt_action t where t.actor = #{et.param0} and t.action = 'login' and DATE_FORMAT(t.date,'%Y') = #{et.param1} ";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetpoinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetpoinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取产品数]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsgetpoinfomationrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    param.put("param1",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param2",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param3",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param4",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param5",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    param.put("param6",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param7",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param8",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    String strSql="select count(1) as YEARPRODUCTCNT from zt_product t where ((YEAR(t.createddate) = #{et.param0} and (t.createdBy =#{et.param1} or t.po = #{et.param2} or t.QD =#{et.param3} or t.RD =#{et.param4} )) or t.id in(select t.product from zt_productplan t left join zt_action t2 on t2.objectID = t.id and t2.objectType = 'productplan' where LEFT(t2.date, 4) = #{et.param5} and t2.actor = #{et.param6} and t2.action = 'opened' and t.product <> 0) or t.id in (select t.product from zt_story t where t.product > 0 and t.openedBy = #{et.param7} and DATE_FORMAT(t.openedDate,'%Y') = #{et.param8} ))";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetpoinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetpoinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetpoinfomationbegin"
    when
    then
    end

//逻辑处理节点[获取需求数]
rule "rawsqlcall3"
ruleflow-group "useryearworkstatsgetpoinfomationrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetpoinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetpoinfomationdefault.get("curyear"));
    String strSql="select count(1) as `yearstorycnt` from zt_story t where t.product > 0 and t.openedBy = #{et.param0} and DATE_FORMAT(t.openedDate,'%Y') = #{et.param1} ";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetpoinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetpoinfomationdefault);//更新fact中变量值
    end

