package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getproducts;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetproductsdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetproductsbegin"
    when
    then
    end

