package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getdevinfomation;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetdevinfomationdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取工时数]
rule "rawsqlcall3"
ruleflow-group "useryearworkstatsgetdevinfomationrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetdevinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetdevinfomationdefault.get("curyear"));
    String strSql="select IFNULL(sum(t.consumed),0) as `YEARESTIMATECNT` from zt_taskestimate t where t.ACCOUNT = #{et.param0} and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetdevinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetdevinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取登录数]
rule "rawsqlcall4"
ruleflow-group "useryearworkstatsgetdevinfomationrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetdevinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetdevinfomationdefault.get("curyear"));
    String strSql="select count(1) as `YEARVISITS` from zt_action t where t.actor = #{et.param0} and t.action = 'login' and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetdevinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetdevinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取动态数]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsgetdevinfomationrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetdevinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetdevinfomationdefault.get("curyear"));
    String strSql="select count(1)  as `YEARACTIONCNT` from zt_action t where t.actor = #{et.param0}  and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetdevinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetdevinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取日志数]
rule "rawsqlcall2"
ruleflow-group "useryearworkstatsgetdevinfomationrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetdevinfomationdefault.get("account"));
    param.put("param1",useryearworkstatsgetdevinfomationdefault.get("curyear"));
    String strSql="select COUNT(1) as `YEARLOGCNT` from zt_taskestimate t where t.ACCOUNT = #{et.param0} and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetdevinfomationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetdevinfomationdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetdevinfomationbegin"
    when
    then
    end

