package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getproducts;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetproductsdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetproductsbegin"
    when
    then
    end

//逻辑处理节点[获取需求数]
rule "rawsqlcall3"
ruleflow-group "useryearworkstatsgetproductsrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param1",useryearworkstatsgetproductsdefault.get("curyear"));
    String strSql="select count(1) from zt_story t where t.product > 0 and t.openedBy = #{et.param0} and DATE_FORMAT(t.openedDate,'%Y') = #{et.param1} ";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetproductsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetproductsdefault);//更新fact中变量值
    end

//逻辑处理节点[获取产品数]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsgetproductsrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param1",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param2",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param3",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param4",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param5",useryearworkstatsgetproductsdefault.get("account"));
    param.put("param6",useryearworkstatsgetproductsdefault.get("curyear"));
    String strSql="select count(1) as YEARPRODUCTCNT from zt_product t where ((YEAR(t.createddate) = YEAR(now()) and (t.createdBy =#{et.param0} or t.po = #{et.param1} or t.QD =#{et.param2} or t.RD =#{et.param3} )) or t.id in(select t.product from zt_productplan t left join zt_action t2 on t2.objectID = t.id and t2.objectType = 'productplan' where LEFT(t2.date, 4) = left(now(),4) and t2.actor = #{et.param4} and t2.action = 'opened' and t.product <> 0) or t.id in (select t.product from zt_story t where t.product > 0 and t.openedBy = #{et.param5} and DATE_FORMAT(t.openedDate,'%Y') = #{et.param6} ))";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetproductsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetproductsdefault);//更新fact中变量值
    end

//逻辑处理节点[获取计划数]
rule "rawsqlcall2"
ruleflow-group "useryearworkstatsgetproductsrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetproductsdefault.get("curyear"));
    param.put("param1",useryearworkstatsgetproductsdefault.get("account"));
    String strSql="select count(1) from zt_productplan t left join zt_action t2 on t2.objectID = t.id and t2.objectType = 'productplan' where LEFT(t2.date, 4) = #{et.param0} and t2.actor = #{et.param1} and t2.action = 'opened' and t.product <> 0";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetproductsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetproductsdefault);//更新fact中变量值
    end

