package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.updateinfo;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsupdateinfodefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService useryearworkstatsservice;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取测试用户信息]
rule "deaction3"
ruleflow-group "useryearworkstatsupdateinfodeaction3"
    when
    then
    useryearworkstatsservice.getQaInfomation(useryearworkstatsupdateinfodefault);
    update(useryearworkstatsupdateinfodefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsupdateinfobegin"
    when
    then
    end

//逻辑处理节点[获取研发用户信息]
rule "deaction2"
ruleflow-group "useryearworkstatsupdateinfodeaction2"
    when
    then
    useryearworkstatsservice.getDevInfomation(useryearworkstatsupdateinfodefault);
    update(useryearworkstatsupdateinfodefault);//更新fact中变量值
    end

//逻辑处理节点[获取产品经理信息]
rule "deaction4"
ruleflow-group "useryearworkstatsupdateinfodeaction4"
    when
    then
    useryearworkstatsservice.getPoInfomation(useryearworkstatsupdateinfodefault);
    update(useryearworkstatsupdateinfodefault);//更新fact中变量值
    end

//逻辑处理节点[获取标题]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsupdateinforawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsupdateinfodefault.get("curyear"));
    param.put("param1",useryearworkstatsupdateinfodefault.get("realname"));
    String strSql="select CONCAT_WS('',#{et.param0},'年工作内容统计一览表 —— ',#{et.param1}) as Title from dual";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsupdateinfodefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsupdateinfodefault);//更新fact中变量值
    end

