package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getprojects;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetprojectsdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取日志数]
rule "rawsqlcall2"
ruleflow-group "useryearworkstatsgetprojectsrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetprojectsdefault.get("account"));
    param.put("param1",useryearworkstatsgetprojectsdefault.get("curyear"));
    String strSql="select COUNT(1) from zt_taskestimate t where t.ACCOUNT = #{et.param0} and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetprojectsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetprojectsdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetprojectsbegin"
    when
    then
    end

//逻辑处理节点[获取工时数]
rule "rawsqlcall3"
ruleflow-group "useryearworkstatsgetprojectsrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetprojectsdefault.get("account"));
    param.put("param1",useryearworkstatsgetprojectsdefault.get("curyear"));
    String strSql="select sum(t.consumed) from zt_taskestimate t where t.ACCOUNT = #{et.param0} and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetprojectsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetprojectsdefault);//更新fact中变量值
    end

//逻辑处理节点[获取动态数]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsgetprojectsrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetprojectsdefault.get("account"));
    param.put("param1",useryearworkstatsgetprojectsdefault.get("curyear"));
    String strSql="select count(1) from zt_action t where t.actor = #{et.param0}  and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetprojectsdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetprojectsdefault);//更新fact中变量值
    end

