package cn.ibizlab.pms.ibiz.logic.useryearworkstatslogic.getqainformation;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.UserYearWorkStats useryearworkstatsgetqainformationdefault;
global cn.ibizlab.pms.core.ibiz.service.IUserYearWorkStatsService iBzSysUseryearworkstatsDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[获取登录次数]
rule "rawsqlcall4"
ruleflow-group "useryearworkstatsgetqainformationrawsqlcall4"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetqainformationdefault.get("account"));
    param.put("param1",useryearworkstatsgetqainformationdefault.get("curyear"));
    String strSql="select count(1) as `YEARVISITS` from zt_action t where t.actor = #{et.param0} and t.action = 'login' and DATE_FORMAT(t.date,'%Y') = #{et.param1} ";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetqainformationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetqainformationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取创建bug数]
rule "rawsqlcall2"
ruleflow-group "useryearworkstatsgetqainformationrawsqlcall2"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetqainformationdefault.get("account"));
    param.put("param1",useryearworkstatsgetqainformationdefault.get("curyear"));
    String strSql="select count(1)  as `YEARBUGCNT` from zt_bug t where t.product > 0 and t.openedBy = #{et.param0}  and DATE_FORMAT(t.openedDate,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetqainformationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetqainformationdefault);//更新fact中变量值
    end

//逻辑处理节点[获取创建用例数]
rule "rawsqlcall3"
ruleflow-group "useryearworkstatsgetqainformationrawsqlcall3"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetqainformationdefault.get("account"));
    param.put("param1",useryearworkstatsgetqainformationdefault.get("curyear"));
    String strSql="select count(1) as `YEARCASECNT` from zt_case t where t.product > 0 and t.openedBy = #{et.param0} and DATE_FORMAT(t.openedDate,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetqainformationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetqainformationdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "useryearworkstatsgetqainformationbegin"
    when
    then
    end

//逻辑处理节点[获取动态数]
rule "rawsqlcall1"
ruleflow-group "useryearworkstatsgetqainformationrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",useryearworkstatsgetqainformationdefault.get("account"));
    param.put("param1",useryearworkstatsgetqainformationdefault.get("curyear"));
    String strSql="select count(1)  as `YEARACTIONCNT` from zt_action t where t.actor = #{et.param0}  and DATE_FORMAT(t.date,'%Y') = #{et.param1}";
    java.util.List<JSONObject> entities=iBzSysUseryearworkstatsDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0 && !ObjectUtils.isEmpty(entities.get(0))){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            useryearworkstatsgetqainformationdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(useryearworkstatsgetqainformationdefault);//更新fact中变量值
    end

